### ISSUE TITLE
Migrations: Support x64 assemblies in package manager console commands

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#1074]
This is a sub-issue of #1058.

One idea I had was to try and use a compatible platform (x86 or AnyCPU) if present, and give a nice error message if one isn't available.

**Comment by vmsgsp** [comment]
Are there any plans when the Entity Framework Commands (Add-Migration, etc.) will be available for x64 Assemblies as well? We are deprecating 32bit builds and it is not nice being forced to continue with 32bit support just because tools don't support 64 bit.
Therefore, as an alternative to the Package Manger Console scripts of Entity Framework Commands, I am using the Microsoft.Data.Entity.Design.MigrationsOperations class in a C# console application in order to generate my migrations. This works quiet well, except that I also have to mimic the behavior of adding the generated files to the csharp project file (using EnvDTE automation for this, which seems to be deprecated with Visual Studio 2015).
Maybe you could enhance the Microsoft.Data.Entity.Design.MigrationsOperations so that it adds the generated files to the project file (and removes in case of Remove-Migration)?
The big advantage I see with this C# console application approach is that we can debug our model builders when being called by the Entity Framework Commands (which is not that easy when running Package Manager Console Scripts).

**Comment by bricelam** [comment]
@vmsgsp Yes, the current plan (for #5334) is to execute commands out-of-process which will enable x64 configurations to work.

**Comment by vmsgsp** [comment]
@bricelam Will this x64 support also be implemented for Full .NET (EF7, .NET 4.6)? In #5334 there is only the keyword ".NET Core".

**Comment by bricelam** [comment]
Yes

**Comment by bricelam** [comment]
We ditched app domains for processes in #6288. This "just works" now.

**Comment by chandanpednekar** [comment]
@bricelam, I am using EF 6.2 and .NET 4.7. I am executing add-migration in x64. It does not work for me. I think that is expected ?!

**Comment by bricelam** [comment]
Yes, EF6 executes inside the VS process which is 32-bit. EF Core executes out-of-process which enabled us to support 64-bit.

**Comment by bricelam** [comment]
You may be able to make it work by building as AnyCPU (without Prefer 32-bit)
