### ISSUE TITLE
Review usage of CompositeEntityKeyFactory.Create

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#1093]
It returns EntityKey.NullEntityKey if any of the key components are null. However there are code paths in the state manager that assume the method always returns a valid key.

**Comment by rayao** [comment]
Another problem I encountered which could be related to this one.
When primary key of a entity is not of integer type, Include() call will result in an ArgumentNullException.

I looked through some EF7 code today and maybe I’ve got the root cause of this problem that I encountered.
After Include() is called on an IQueryable<>, I got ArgumentNullException here:

>                EntityFramework.Core.dll!Microsoft.Data.Entity.Utilities.Check.NotNull<Microsoft.Data.Entity.ChangeTracking.EntityKey>(Microsoft.Data.Entity.ChangeTracking.EntityKey value, string parameterName) + 0x6d bytes        
                EntityFramework.Core.dll!Microsoft.Data.Entity.ChangeTracking.StateManager.TryGetEntry(Microsoft.Data.Entity.ChangeTracking.EntityKey keyValue) + 0x3b bytes 
                EntityFramework.Core.dll!Microsoft.Data.Entity.Query.QueryBuffer.GetEntity(Microsoft.Data.Entity.Metadata.IEntityType entityType, Microsoft.Data.Entity.Metadata.IValueReader valueReader, bool queryStateManager) + 0xf1 bytes     
                EntityFramework.Core.dll!Microsoft.Data.Entity.Query.QueryBuffer.GetEntity(Microsoft.Data.Entity.Metadata.IEntityType entityType, Microsoft.Data.Entity.Metadata.IValueReader valueReader) + 0x32 bytes   
                EntityFramework.Core.dll!Microsoft.Data.Entity.Query.QueryBuffer.GetTargetEntity(Microsoft.Data.Entity.Metadata.IEntityType targetEntityType, Microsoft.Data.Entity.Metadata.IValueReader valueReader, System.Collections.Generic.ICollection<Microsoft.Data.Entity.Query.QueryBuffer.BufferedEntity> bufferedEntities) + 0x42 bytes   
                EntityFramework.Core.dll!Microsoft.Data.Entity.Query.QueryBuffer.Include.AnonymousMethod__0(Microsoft.Data.Entity.Metadata.IValueReader valueReader) + 0x4c bytes           

From code I can see StateManager.TryGetEntry will first ensure the EntityKey is not null, but in QueryBuffer.GetEntity, before calling into StateManager, there’s no null check, only this:
if (entityKey == EntityKey.NullEntityKey)
{
return null;
}
EntityKey.NullEntityKey is an object, not null, so if entityKey is null, a call to StateManager.TryGetEntry will still happen.
So is there any EntityKeyFactory which return null instead of EntityKey.NullEntityKey? It seems SimpleNullableEntityKeyFactory does.

From my experiments, if key is of int type, an Include() with nullable foreign key won’t cause exception, I believe that’s because SimpleEntityKeyFactory is actually used for int type key. And if key is of string type, an Include() with nullable foreign key will throw, maybe an indication that SimpleNullableEntityKeyFactory is used.

It’s also possible that my understanding is wrong, please correct me in that case.
