### ISSUE TITLE
Decide on use of property setters vs fields

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1526]
We currently use the backing field by convention in some scenarios. We should revisit if this is the right thing to do by convention, or whether we should just use setters and allow folks to swap to backing field access if they want to.

**Comment by divega** [comment]
Per #4314 by default we will only discover properties with public getters and public or non-public setters (with the exception of collection navigation properties which don't require setters). 

Customers should still be able to explicitly pull in properties into the model that would otherwise not be discovered and have EF use backing fields for materialization and fixup.

I have created a separate issue for:
- Considering having an alternate "map all fields" discovery convention #4356
- Enable model-level entity properties to be associated to a backing field but no property getter or setter #4357

Closing as I believe there is nothing else to track here.
