### ISSUE TITLE
Throw when System.Transactions.Transaction.Current is set

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1584]
When discussing https://github.com/aspnet/EntityFramework/issues/1530 we decided not to support TransactionScope. We decided we should detect if someone is trying to though and throw so it is clear it's not supported. We should have a flag to disable throwing in case folks are using TransactionScope for other reasons and EF code just happens to be hit in the block.

**Comment by davidroth** [comment]
@rowanmiller What is the motivation behind this decision?
Does this mean that TransactionScopes will be completely unsupported or is there a switch to enable ambient transaction enlisting? (Does the flag to disable throwing enable the enlisting?)

**Comment by popcatalin81** [comment]
@rowanmiller we use Transaction scope for two reasons:
1. it is the mechanism to propagate transactions through WCF
2. We use the repository pattern and the way to group multiple repository submit changes calls is through a Transaction scope

If Transaction scopes are not supported by default, what will be the option to use them together with EF7? Will it even be possible in some way?

**Comment by divega** [comment]
@popcatalin81 @davidroth We won't try to disable connections from auto-enlisting on desktop .NET. Instead we will throw in the right places so that you won't assume that EF can work with System.Transactions, e.g. on `SaveChanges()` but perhaps also at any time a connection is open.

There are several reasons throwing an exception is our first choice:

1. Although System.Transactions looks compelling it does a lot of magic and can cause a lot of pain on the edges when the magic falls down, e.g. unintended transaction promotion can have significant impact
2. We have a transaction API that more closely reflects what you can actually do with database transactions on a single connection (the underlying connection of the DbContext) and doesn't have those pain points
3. When you need to talk to the same database from multiple repositories you are often better off sharing the connection than resorting to System.Transactions
4. Supporting System.Transactions (TransactionScope and also CommittableTransaction) would introduce complexity in our code
5. In general we can't assume we have access to a distributed transaction coordinator on device and cloud scenarios 
6. System.Transactions isn't even there on .NET Core based platforms

All that said, there is no good replacement for System.Transactions when you really need distributed transactions, e.g. in enterprise scenarios with multiple databases. We can consider factoring connection and transaction management in such a way that the behavior can be overridden (see #1529) but it is hard to prioritize doing more given all the issues. 

More feedback on this is would be welcome.

**Comment by popcatalin81** [comment]
@divega 

Lots of times we simply use System.Transactions to create ambient transactions in higher layers of the application using an transparent mechanism, and not inside the data access layer where such a decision cannot be made because the business layer does multiple calls to the DA layer. And for this particular scenario we actively avoid DTC and transaction promotion.

As long as EF7's connection and transaction management is flexible enough (Point 2 and 3) I think it would not be a problem to emulate ambient transactions.

But please do not throw when an Ado.Net connection that is *not owned* by the DbContext is enlisted in an ambient transaction. Then we can manage ambient transactions in client code.

**Comment by davidroth** [comment]
@divega We use TransactionScope to create ambient transactions in higher layers and the call several business functions inside it.

Ex:
```csharp
using(var scope = TransactionScopeUtil.CreateScope())
{
 service1.PerformSomeBusinessLogic_WhichInvolesDatabaseUpdates(); // May create own dbcontext
 service2.PerformSomeBusinessLogic_WhichInvolesDatabaseUpdates(); // may create own dbcontext

 scope.complete();
}
```

Each service may also create its own independent DBContext and call "SaveChanges" on it. This works really nice in EF6 as each DbContext enlists in the ambient transaction and all data changes will be atomically committed when calling scope.Complete();

We really just use TransactionScope for this, we do not use MSDTC and actively avoid a promotion to MSDTC by avoiding all parallel database calls within an open transaction scope.

So will this be possible in EF7? Or do we have to write our own implementation of "TransactionScope" which then passes the connection to the nested DbContexts?
