### ISSUE TITLE
MARS requirement gives issues for DB's that don't support this

### ISSUE THREAD

**Issue by bartdevriendt** [aspnet/EntityFramework#1665]
Working on my provider for MySQL i'm running into troubles with the MARS requirement.  As MySql doesn't support this all the outer queries fail with the already open DataReader exception.   I managed to workaround this by catching the exception in my DB Command wrapper object and opening a new connection to the database and creating a reader on this new connection.  Luckily the MySql connector has connection pooling by default so not too many connections are opened, but still all the "cloned" connections are untracked and undisposed.

Is there a possibility this MARS requirement is reconsidered, or some kind of option is introduced to turn this of ?

**Comment by rowanmiller** [comment]
@anpete - can you drive some discussion around this

**Comment by anpete** [comment]
@bartdevriendt This is really just a limitation of our _default_ query compiler in our core provider framework - one we will probably address at some point. A couple of things to consider:

1) When compiling a query, you have complete control over the expression tree produced and you can opt out of our default behavior by overriding the appropriate VisitX method in your query model visitor.
2) Have you considered completely buffering the results from the outer reader so that you can close that reader?

Cheers,
Andrew.

**Comment by bartdevriendt** [comment]
By replacing all necessary services and overriding the default behaviour it would indeed be possible to overcome the limitation.  Closing this issue.

**Comment by roji** [comment]
@bartdevriendt, @anpete, @rowanmiller, Npgsql has the same issue with the lack of MARS support.

Since non-MARS is a pretty common case (maybe even the normal case?), doesn't it make sense for the EF core to contain a compatible query compiler and/or necessary services? This way driver writers would simply choose the non-MARS one rather than reimplementing their own?

On a related note, I'm (still) very unfamiliar with the actual mechanics going on, but it seems odd for something as simple as an `Include()` to depend on MARS, even in the default query compiler. Wasn't this handled without MARS in EF6? Was there a big architecture change that made it impossible to continue doing so? And handling that by buffering up the entire outer reader seems very problematic from a performance/memory-usage perspective.

Thanks for any help/pointers on how to proceed with this...

**Comment by roji** [comment]
Just to add a little on my last note...

Npgsql is nearing the end of a pretty huge rewrite (3.0.0-beta.1 has just been released). The option of implementing MARS via SQL cursors does exist, but doing it in a correct and efficient way would be a pretty big task that I really want to avoid for the immediate future. I'd also like to avoid implementing a performance-problematic solution such as buffering an entire reader (a sort of poor man's MARS, I guess).

So if EF7 is compatible with an efficient, non-MARS way of doing things, that would be ideal - and it would be great to have the necessary services available for use in EF7 itself. Otherwise we really need to think we to do on our side...

**Comment by divega** [comment]
Hi @roji, de actually did adress this issue in PRs https://github.com/aspnet/EntityFramework/pull/2177 and https://github.com/aspnet/EntityFramework/pull/2198. Unfortunately the change appears in GitHub as if it had been force-pushed so there aren't any changes associated with the PR, but in summary providers override 'RelationalConnection.IsMultipleActiveResultSetsEnabled' to control the EF runtime behavior. If a provider returns 'false' EF will automatically buffer the remaining results of any pending query before starting a new one. Hope this helps.

**Comment by roji** [comment]
@divega, thanks for the quick answer. Great, I'll go and implement that and will write back if there are any issues.

Do I understand correctly that this non-MARS simply buffers the data from the open reader in memory? Do you guys view this as an adequate solution from a performance perspective? At least for stuff like simple `Include`s, I was expecting simple SQL joins rather than any reliance on MARS or buffering...

(apologies in advance if I'm misunderstanding things, am not very familiar with EF internals)

**Comment by divega** [comment]
@roji It depends :smile: but we believe that in many cases this will be better than the alternative. 
@anpete implemented it so he may want to correct me or provide more details, but here are a couple of points that should help explain it:

1. The implementation of `Include()` still uses JOINs in cases in which they would preserve the cardinality of the results. It only switches to multiple queries when it needs to traverse a collection navigation property, a case in which JOINs would cause an explosion of the number of rows and data redundancy in the results. 

2. Independently of the implementation of `Include()` an application can attempt to execute a query while iterating over the results of another query which would require MARS or buffering to work correctly. The design addresses (or at least has the potential to address) that scenario as well.

**Comment by divega** [comment]
@rowanmiller @anpete I assigned the beta5 milestone to this but I suspect it might have been addressed for beta4. Could you check if is correctly resolved?

**Comment by roji** [comment]
@divega, thanks for the patient explanation.

Regarding your first point, I can definitely see cases where what you describe makes sense. I'll let you guys know if I see an instance where MARS/buffering behavior seems needless.

Regarding your second point, I wasn't aware that EF attempts to allow multiple concurrent queries regardless of underlying database MARS support. At the ADO.NET level this is certainly not the case - since MARS isn't a standard ADO.NET feature it's the application writer's responsibility to use it or not, and trying to execute multiple queries without underlying MARS support leads to an exception. I'm not sure I see why it makes sense to always allow MARS-like semantics in EF (as opposed to ADO.NET), but if that's a design decision then so it is...

**Comment by roji** [comment]
Just FYI, Include and other previously failing stuff is now working well with Npgsql since EF no longer assumes MARS. Will report any issues.

**Comment by roji** [comment]
@divega, @anpete and others, I'd like to hear your thoughts about something.

EF7 is now OK with providers which don't support MARS, but it seems that performance will be significantly better for those who do support it - no need to buffer the entire reader in client-side memory.

So a thought I had was to fall back on server-side cursor-based buffering  rather than on "total" buffering as is done now. This would allow EF7 to process results in chunks, potentially reducing memory usage in a dramatic way. I'm not sure as to the standards status of server-side cursors: SQL seems to allow cursors only in embedded SQL and in modules, but databases seem to allow them in regular SQL too? I also don't know how many other databases are in PostgreSQL's position, i.e. support server-side cursors but don't support MARS.

Another option here would be for Npgsql itself to implement "MARS" on top of server-side cursors, which would be totally unrelated to EF7, but then other databases wouldn't benefit from this.

Any thoughts on the above?

**Comment by divega** [comment]
@anpete and I talked briefly about this and we actually don't anticipate the overhead introduced by buffering to be that significant for most common scenarios. Of course it might make sense to do something different for Npgsql but I would suggest measuring the impact (which is possibly easier done using SQL Server flipping the MultipleActiveResults flag in the connection) before investing a big chunk of time on this :smile:

**Comment by roji** [comment]
OK, thanks. I'll try to play around with it a bit and report if I have any interesting/conclusive results. In any case it's not for right away...

**Comment by kskalski** [comment]
Is the support for non-MARS db provides in EF.Core supposed to handle concurrent queries done by the client? I'm getting 
 Microsoft.EntityFrameworkCore.Query.Internal.NpgsqlQueryCompilationContextFactory[1]
 An exception occurred in the database while iterating the results of a query.
      System.InvalidOperationException: An operation is already in progress.

which seems to be happening when I have a long query being executed for one web request while the other web request tries to execute another query.

I'm using 
   "Microsoft.EntityFrameworkCore.Relational": "1.0.0-rc2-final",
   "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0-rc2-release1",
   "Npgsql": "3.1.2",

I could do some locking on the application side, but comment from https://github.com/aspnet/EntityFramework/issues/1665#issuecomment-105246302 indicates it should work fine on its own.

**Comment by divega** [comment]
@kskalski it doesn't handle multiple overlapping queries initiated by the application. We only built an alternative mechanism to handle the situation in which EF Core itself initiates multiple queries to retrieve the results of queries with `Include()` to collections. You can just use something like `ToList()` on the first query to finalize the execution before you start the second one, or you can query in two separate `DbContext` instances so that two separate connections are used.

**Comment by inossidabile** [comment]
Does it mean that you literally can't use "1-many" `Include` calls without MARS?

**Comment by roji** [comment]
@inossidabile you definitely can do 1-many includes - each EF Core provider declares whether it supports MARS or not, and the EF Core will alter its behavior based on that to avoid sending concurrent statements where that's not supported. However, this doesn't prevent users from accidentally trying to use the same DbContext (and therefore connection) concurrently, triggering concurrent usage exceptions.

**Comment by inossidabile** [comment]
Well that's strange. I'm running a single request from a properly injected context and if it uses `Include` it throws this error. So it's only related to having include or not. Also with having include it does two queries indeed.

**Comment by roji** [comment]
This repository is for Entity Framework Core, not EF6. You're better off opening an issue with a code sample at your provider's repo (Pomelo).

**Comment by inossidabile** [comment]
Yeah, I use that really. Miswritten. I didn't realise that could be a provider issue. Thanks!

**Comment by divega** [comment]
@inossidabile filing an issue on the Pomelo provider repo sounds like a good idea. 

But in case it helps, that provider is for EF Core and not EF6 though. And EF6 never used MARS for Include queries.

**Comment by inossidabile** [comment]
Yeah, like I said, I mistakenly wrote that. I'm using EF Core.

**Comment by PeterKneale** [comment]
Does this mean that the below `async` scenario will only work with `MsSqlServer` with `MARS` enabled?
I am attempting to port an application from `MsSqlServer` to `Postgres/NPgSql` using EF Core 2 and would be surprised if this was not possible because of the user of the async queries. Is that the case?

```cs
var task1 = _context.Users.SingleAsync(x => x.Id == 1);
var task2 = _context.Projects.SingleAsync(x => x.Id == 1);

Task.WaitAll(task1, task2);

var user = task1.Result;
var project = task2.Result;
```

**Comment by ajcvickers** [comment]
@PeterKneale In general WaitAll should not be used with EF Core because EF cannot execute multiple queries in parallel. If this is working on SQL Server (or for any provider) then it is because EF is serializing the two queries to run consecutively. While this will likely work for cases only involving queries because of the way the internal query state machine works, it will likely not work if the async calls are doing anything that is strictly not just a query. It's pretty hard to know when that's the case, and since there is no concurrency advantage to doing this, it means it's best to just not use WaitAll at all.
