### ISSUE TITLE
Be consistent and clear about what kind of connections are supported by the SQL Server provider

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1676]
If we want people to use the EF SQL Server provider with a different ADO.NET provider (such as a wrapped provider) then we should be explicit about this, make sure that we don't depend on an SQL Server-specific APIs and types, and test it.

**Comment by dazinator** [comment]
Could this warrant a rename of the provider itself? I.e to something like "Transact Sql Provider" ?

I know t-sql generally means SQL server as the target database, but thought id mention this anyway, as food for thought, as it would be entirely upon the implementation of the ado.net provider used at runtime as to whethet SQL server is actually ever involved..

**Comment by rowanmiller** [comment]
@dazinator - The provider is still very much specific to SQL Server (generates SQL Server specific syntax etc.). Historically third party tools have used the technique of wrapping DbConnection to achieve logging etc (Glimpse is one example of this). For this reason, we want to avoid ever assuming that something is a `SqlConnection` even in a provider that can only be used to target SQL Server.

**Comment by dazinator** [comment]
Thanks @rowanmiller - I do understand, and I am familiar with glimpse - and I am grateful that you guys are going to make modifications to accommodate this!

Perhaps my suggestion seems silly, but it seemed to me, once you make this EF provider agnostic about the actual ADO.net provider used (connection, command etc etc), then the only thing that would actually tie it to a physical SQL Server is the fact that the ADO.NET provider used at runtime will be communicating with a physical SQL server - and by and large this will be case, however, I can't see anything technically stopping me from writing an ADO.Net provider (that accepts the T-SQL commands from EF as its command language) but that actually communicates with "ACME system" i.e not SQL server. For that reason, once this flexibility is present, "SQL Server provider" seemed like not the ideal name in that context.

I know that what I have explained above is probably not the intended use case for this feature, however I have looked at the shortest path so that I can get EF7 to work against Microsoft Dynamics CRM - and I had 2 options:

A. Write a new EF provider
B. Leverage the existing SQL Server provider, and then look to leverage my existing ADO.NET provider to handle the T-SQL commands produced by EF (that in turn communicates with CRM)

With option A, there is a greater effort, and I end up either with something that doesn't use ADO.NET at all (and therefore doesn't leverage my existing ADO.net provider at all) or I end up with something that does use ADO.NET, and therefore looks remarkably similar to the existing SQL server provider you guys have written

With option B, I have the benefit that you guys have written the provider already and will maintain it, and I can just focus on my existing ADO.Net provider to make sure it can handle the commands that EF will chuck at it.

Needless to say, option B is looking very attractive for me. Would you consider this an abuse of EF7?

One of the downsides of option B is that consumers would end up using what is known as the "SQL Server Provider" - when in actuality they would be targeting Dynamics CRM. My suggestion to name the  "SQL Server Provider" something like "Transact Sql Provider" was really born out of this concern - as it doesn't make assumptions about the physical data store (as that's handled by the ADO.NET)

**Comment by divega** [comment]
@dazinator thanks for the feedback. Yours is indeed an interesting scenario that would be good to enable, as it is wrapping providers and alternate ADO.NET implementations such as Mono's SqlClient implementation and [OneSql](https://www.nuget.org/packages/OneSql.Client.AdoNet/).

Note that this issue expresses our desire to be clear about what approach we take, and not necessarily constitutes a commitment to make our EF provider agnostic with regards to the underlying ADO.NET provider. At least not yet. 

Doing so certainly has the advantages enumerated above and should be facilitated by provider factories but it has a cost which includes the cost of verifying that it actually works, so it competes with many other high priorities.

Regarding the name, it is not set in stone but it is certainly a provider designed to connect EF7 with recent versions of SQL Server and even it it can be used as the basis to connect to other things that talk T-SQL it would be ideal if its name made it easy to identify its primary purpose.

**Comment by rowanmiller** [comment]
@smitpatel - talk with @divega and @ajcvickers about this one

**Comment by rowanmiller** [comment]
Currently we only use `SqlConnection` directly when connecting to master... and we have an issue to use `Clone()` instead. Everything else should work just fine.
