### ISSUE TITLE
Unintuitive graph behavior with join table

### ISSUE THREAD

**Issue by vossad01** [aspnet/EntityFramework#1916]
When using `TrackGraph` with a join table composed of a composite primary key a new relationship to an existing entity will not be saved, yet may still be available in-memory depending on whether `AsNoTracking` was used.

Specifically, if `AsNoTracking()` is specified, the unsaved relationship is not returned by the query.  However, in the absence of `AsNoTracking` the relationship will exist in the object model even though it will never make it to the database.

What I would have *liked* to happen was the relationship to save; though now looking at the implementation of `KeyValueEntityTracker` I see no way that was going to be accomplished.
I had *expected* a query's retrieved data to be the same whether `AsNoTracking` was specified or not.  In this case, not including the never-saved relationship would seem the correct behavior because it most quickly points to the issue.

I am inclined to think this is all all by design and, with looking at the implementation, I can rationalize how everything is behaving.  However, I do not find the behavior immediately apparent (I expended quite a bit of time trying to figure out why some queries worked and other did not).  Additionally, I do I see an simple way to leverage `TrackGraph` to get the behavior I desire.  Assuming this is all by design, I would consider this usability feedback.

**Model:**
```
internal class MyDbContext : DbContext
{
	protected override void OnConfiguring(DbContextOptions options)
	{
		options.UseSqlServer(@"Server=(localdb)\v11.0;Database=MyContext;Trusted_Connection=True;MultipleActiveResultSets=true");
		base.OnConfiguring(options);
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Person>(
			c =>
				{
					c.ForRelational().Table("Person");

					c.Key(t => t.Id);
					c.HasMany(x => x.PersonEmployers).WithOne().ForeignKey(x => x.PersonId);
				});
		modelBuilder.Entity<Employer>(c => c.Key(t => t.Id));
		modelBuilder.Entity<PersonEmployer>(
			c =>
				{
					c.Key(t => new { t.PersonId, t.EmployerId });

					c.HasOne(t => t.Employer).WithOne().ForeignKey<PersonEmployer>(x => x.EmployerId).Required();
				});
	}
}

public class Person
{
	public Person()
	{
		this.PersonEmployers = new Collection<PersonEmployer>();
	}

	public Guid Id { get; set; }

	public ICollection<PersonEmployer> PersonEmployers { get; protected set; }
}

public class PersonEmployer
{
	public PersonEmployer(Guid personId, Guid employerId)
		: this()
	{
		this.PersonId = personId;
		this.EmployerId = employerId;
	}

	protected PersonEmployer()
	{
	}

	public Employer Employer { get; set; }

	public Guid EmployerId { get; set; }

	public Guid PersonId { get; set; }
}

public class Employer
{
	public Guid Id { get; set; }
}
```

**Demo**
```
internal class Program
{
	public static void Should_save_PersonEmployers()
	{
		MyDbContext dbContext = new MyDbContext();
		dbContext.Database.EnsureCreated();
		dbContext.Database.EnsureDeleted();
		dbContext.Database.EnsureCreated();

		Employer employer = new Employer();
		dbContext.Set<Employer>().Add(employer);
		dbContext.SaveChanges();

		Person patient = new Person();
		patient.PersonEmployers.Add(new PersonEmployer(patient.Id, employer.Id) { Employer = employer });

		var tracker = new KeyValueEntityTracker(updateExistingEntities: false);
		dbContext.ChangeTracker.TrackGraph(patient, tracker.TrackEntity);
		dbContext.SaveChanges();

		// AsNoTracking in the next line greatly changes the behavior
		Person dbPerson =
			dbContext.Set<Person>().AsNoTracking().Include(_ => _.PersonEmployers).Single(_ => _.Id == patient.Id);


		if (dbPerson.PersonEmployers.Count != 1)
		{
                        // Fails with AsNoTracking, else succeeds
			throw new Exception(
				string.Format("Count was {0} but should have been 1", dbPerson.PersonEmployers.Count));
		}
	}

	public static void Main(string[] args)
	{
		try
		{
			Should_save_PersonEmployers();
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
		}

		Console.WriteLine("Press any key to exit...");
		Console.ReadKey();
	}
}
```

**Comment by rowanmiller** [comment]
This is consistent with the design we agreed on... but I agree it is confusing. When discussing the design of TrackGraph we decided that the"'if the key is set then it's existing, if not it's added" logic is overly simplistic and quickly falls down (your case is a perfect example of this). For that reason we removed the overload of TrackGraph that just did this by default (we haven't done an API review yet to decide what to do with KeyValueEntityTracker).

We'll discuss this more on our side to see what we want to do, this is great feedback for that discussion so thank you for taking the time to write it up.

From what you said I think you are already aware of this, but the difference with `AsNoTracking` is because it doesn't return the instances tracked by the context... so any changes made that haven't been saved won't be reflected in the results. In your case though you would expect the changes to have been saved.

**Comment by rowanmiller** [comment]
**Triage** Discussed and decided we will just remove KeyValueEntityTracker (tracked by https://github.com/aspnet/EntityFramework/issues/2176) as this leaves it up to the developer to provide logic that works for their domain model (could be stored state in DTOs, query the database, look at key values, etc.). We will provide clear guidance about how to do these and leave the helper methods in place so that the logic to detect based on key value is still very simple to write.
