### ISSUE TITLE
Migrations :: ForSqlServer() configuration doesn't work with migrations

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1975]
E.g. trying to change Index name by:

```
modelBuilder.Entity<City>().Index("Shadow", "Name").ForSqlServer().Name("My index");
```

This gets ignored and produces index with default name - "IX_City_Shadow_Name"

**Comment by bricelam** [comment]
This work is part of #1904

**Comment by npnelson** [comment]
Is there any kind of workaround for this right now?  I am trying to pluralize my table names using `` builder.Entity<TestModel>().ForSqlServer().Table("TestModels");``  This worked fine in beta3 but fails in beta4.  

Specifically, I like to use LocalDb for some of my tests and it creates the table using the entity name instead of my pluralized name.

If I'm not making any sense, check this repo out for a console based demo using CoreCLR beta4:

https://github.com/npnelson/TestEF7TableNameDemo

**Comment by bricelam** [comment]
To work around, use `.ForRelational()` instead.

**Comment by npnelson** [comment]
Thanks, that worked - I should have thought of that
