### ISSUE TITLE
ModelBuilder: Fluent, constraint APIs should create properties

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#2285]
To illustrate...

```C#
modelBuilder.Entity(
    "Post",
    x =>
    {
        x.Key("Id"); // Throws property 'Id' not found
        x.Index("BlogId"); // Throws property 'BlogId' not found
        x.Reference("Blog").InverseCollection() // OK
            .ForeignKey("BlogId") // Throws property 'BlogId' not found
            .PrincipalKey("Id"); // Throws property 'Id' on entity 'Blog' not found

        x.Property<int>("Id");
        x.Property<int>("BlogId");
    });

modelBuilder.Entity(
    "Blog",
    x =>
    {
        x.Property<int>("Id");
        x.Key("Id");
    });
```

If the shadow properties are created before the constraint calls, everything works.
Referencing Blog works because, I believe, we call GetOrAdd. We should consider doing the same for properties. Effectively stubbing them out in metadata to be fully defined later.

Implementing this may be a double-edged sword, however, because instead of catching typos, we'll just create another property.

:warning: If we don't allow this, we'll need to fix the issues this causes in the model snapshot by topologically sorting entity types and breaking foreign key cycles instead.

**Comment by AndriySvyryd** [comment]
@bricelam, @ajcvickers 
For properties we need to have a type. We could make the above code work by using a temporary type and throwing in validation if it hasn't been replaced. But then the conventions will run and use the temporary type, anything they do will need to be fixed when the actual type is specified. I think that's introducing more pitfalls without much value as in this scenario there's no reason that properties can't be declared first.

That said this should work for non-shadow entity types if the property names match CLR properties as in that case you could skip the Property call.

**Comment by ajcvickers** [comment]
@divega My understanding of the general principal at play here is that we want this API to generally work for building models regardless of whether CLR types are present or not. If that is the case, then we should do the work to make both cases behave in the same way even though it adds complexity to our code because it gives the app developer a consistent experience using just one API to do whatever they need to do.

Beyond that, we can decide that instead it mostly works the same, but there are limitations, in which case we should throw helpful exceptions for when the developer "does it wrong" and we should make sure that when we are generating code (i.e. in Migrations) that we always follow these rules and don't "do it wrong".

**Comment by divega** [comment]
An alternative point of view is that passing an actual CLR type (which aligns better with what @AndriySvyryd said) is a shortcut for specifying an entity type name + the shape of the entity, i.e. all its properties and types. If you are specifying an entity without a CLR type it is fair to say that you need to provide an exhaustive description of its shape using some other means. 

If it wasn't expensive I would be inclined to say we need to support just the same pattern independent of order as Brice put in (but making sure you don't miss declaring any of the properties by calling the `Property<T>(name)` API). Since I am hearing (and already suspected) that this would be expensive, I think we need to compromise. 

Not sure what the compromise should look like, e.g. we could just say that you need to call '.Property<T>(name)` before anything else as currently happens or we could make this overload of `Entity(typeName)` different so that before you start fiddling with the configuration you need to specify the shape of the entity, e.g. with a builder that only knows about properties.

Thoughts?

**Comment by AndriySvyryd** [comment]
@ajcvickers We don't have the same behavior for API that deals with shadow and non-shadow properties as per our discussions the benefit of being able to skip redundant configuration for CLR properties is greater than the benefit of having the same behavior, since most users will be using CLR properties.
I believe the same applies here. Having the CLR information is something we cannot mimic reliably.

From a user's stand point I don't think anyone would be surprised to know that they need to provide more configuration for shadow stuff, but they could be annoyed to have to do the same for CLR since in that case there's enough information for us to make an educated guess about their intent.

If they want the same configuration pattern in both cases they are free to specify the redundant configuration for CLR case.

**Comment by ajcvickers** [comment]
@divega "passing an actual CLR type is a shortcut for specifying an entity type name + the shape of the entity" I don't think this is true. Properties may be brought in by convention, but otherwise it just brings in the type with no properties.

@AndriySvyryd Agreed that not having the same behavior was how it was designed, and I like that design, and it works well when it is a fluent API for building runtime models either written and edited by an app developer or possibly scaffolded. However, we have now decided that this API is more general purpose than that. Specifically, it should work for creating an entire model snapshot with everything in shadow state. Generally, it should be a general purpose model building API (i.e. not necessarily for runtime models) and should work consistently with shadow and CLR entities so that a developer can build whatever kind of model they want for whatever kind of purpose they want using a consistent API. I'm fine with us compromising on that, but the more we compromise, the less advantage there is in having one model builder to rule them all.

**Comment by AndriySvyryd** [comment]
@ajcvickers For the scenario where the entire model is specified and it doesn't rely on conventions it is consistent as it allows to configure the CLR entity types the same way as the shadow ones. We can make it more consistent the other way around by making "finding unconfigured CLR property by name" an explicit convention, however I am not convinced if that has enough value.

We are obviously not consistent between the behavior of ModelBuilder with conventions and one without.

**Comment by ajcvickers** [comment]
@AndriySvyryd In the above code, without conventions, if Blog is a CLR entty type, then calling Key will first bring Id into the model and then make it the primary key. Therefore, you can call Key before calling Property.  If Blog is a shadow entity type, then calling Key will throw. Therefore, with shadow entity types there is an order dependency in the API which does not exist for CLR entity types. This is the inconsistency.

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes, I can see that. My point is that is we could make it throw for CLR as well to achieve consistency. Making it work for shadow entities requires our code to make assumptions and will almost certainly cause edge case bugs.

**Comment by bricelam** [comment]
If order ends up mattering, we'll instead need to topologically sort entity types in the model snapshot and break foreign key cycles. Please keep this in mind when weighing the cost.

**Comment by AndriySvyryd** [comment]
@bricelam That can be avoided if the model building is split into two parts:
1. Configure everything on all the entity types except relationships
2. Configure relationships

**Comment by ajcvickers** [comment]
@AndriySvyryd I see--you mean it would throw for CLR types when there are no conventions, but preserve the desired behavior for CLR types when conventions are present. I don't think this really moves us towards a world where you get a model builder and it just works. You now have to know whether conventions are being used or not. In other words, even if you fully specify your model, it may or may not work depending on whether there are CLR types and whether there are conventions,

My opinion, assuming we want one model builder to rule them all, is that we make it more complicated and accept the consequences of that (this was the decision that was previously made) or we compromise and add a caveat to the "works everywhere model builder" and make sure we generate code, etc. that compensates for this. In this case, always generate Property calls first in the snapshot. I'd prefer the latter, but I think it deviates from the decision we made, and so I think @divega should make the call since he was pushing for "one model builder to rule them all".

**Comment by divega** [comment]
I am ok with this compromise and I think what @AndriySvyryd proposed before, to split all the model building code we generate into two phases (the first one to configure everything but relationships and the second one to configure the relationships) should work. FWIW, I had done that by hand in the past (minus the exhaustive configuration of the properties) and it felt good :smile:

**Comment by AndriySvyryd** [comment]
@divega mentioned that we could have a more consistent experience if the API for adding a shadow entity type would have a required parameter for specifying the property names and types

**Comment by ajcvickers** [comment]
@divega @AndriySvyryd But adding a non-shadow CLR entity type does not add properties. If you have conventions enabled, then a convention may kick in that will then bring in properties by convention, but to me this is different both conceptually and practically since the convention can be removed and/or changed.

**Comment by AndriySvyryd** [comment]
@ajcvickers Well we can choose to only add the properties specified in this way for shadow entity types if the property discovery convention is present. Basically it allows the user to provide the same information we would extract from the CLR type in the equivalent call.

**Comment by ajcvickers** [comment]
To me it feels like a band-aid API over a leaky abstraction.

**Comment by ajcvickers** [comment]
Thinking about this more, I think we should go back to our original decisions on the model builder API and say that if you are using shadow entity types or shadow properties on CLR entity types then there are constraints with that, and the primary constraint is that you must tell us about these properties before you use them since we have no reasonable way of inferring metadata about them. I think we thought that this was find when using the model builder to build a runtime model, and I still think this is fine. In other words, its okay for shadow stuff to have some different requirements than regular stuff.

So then we also have the decision to use the model builder for snapshots. Then it follows that the snapshot must use the model builder in the way it was designed. This means that because it is using shadow types it must follow the rules for shadow types. So it should be the snapshot code that uses the model builder correctly, and not the model builder that should change to accommodate the snapshot. So the snapshot should make a call to Entity and then repeated calls to Property for every entity type to fully define each entity type. Because that's how the model builder works.

If we add new APIs, it doesn't make the snapshot code significantly better, because it will still need to be factored to define each entity type and all properties before using them. It just makes it one long call instead of a chain/series of short calls.

**Comment by rowanmiller** [comment]
>  I think we should go back to our original decisions on the model builder API and say that if you are using shadow entity types or shadow properties on CLR entity types then there are constraints with that, and the primary constraint is that you must tell us about these properties before you use them since we have no reasonable way of inferring metadata about them.

I agree... I was actually just doing this with a model where I wanted to define a key in shadow state because I was re-using an existing domain object as part of an EF model. The logical code to me was to define the property and then configure it as the key.

**Comment by divega** [comment]
I know what we have isn't necessarily broken if you look at it with the right mindset. I am just tinkering with various ideas to see if I can find a story that feels more consistent and simpler (what Andriy described is just one of the directions). I know it is possible that I won't find one.

**Comment by smitpatel** [comment]
At present model snapshot is created with following guidelines.
- Sort entity types topologically based on their hierarchy
- For each entity type configure in following order (excluding relationships)
  - BaseType declaration
  - Properties declaration
  - Keys declaration
  - Indices declaration
  - entity type annotations
- Configure all relationships

The sorting is introduced because in case of inheritance the derived entity type can use properties from base type for declaration.
ModelSnapshot is already adhering to guidelines suggested in discussion. Other than model snapshot we are not generating code which uses shadow state with modelbuilder.
No changes required with current decision :smile:
