### ISSUE TITLE
Deployment and Database Creation/Migration

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#244]
For local development we introduced a piece of middleware in ASP.NET 5 that provides instruction on using migrations.

We are currently working to replace the 'apply migrations on app start' functionality with something better.

**Comment by rowanmiller** [comment]
Agreed upon design is here https://github.com/aspnet/EntityFramework/wiki/Visual-Studio-Publish-Integration

**Comment by divega** [comment]
Assigning temporarily to myself to follow up with the tooling folks to figure out how we land this in RC2.

**Comment by ryanerdmann** [comment]
I know this issue is primarily about the VS right-click Publish integration story, but do you also have any recommendations for how to manage migrations for customers using git deployment (Kudu) to Azure?

I have several web apps using that deployment scenario, and for now I’ve just settled with using `ef migrations script -i` and running the script from my client machine.  Would it make sense instead to use a custom Kudu deployment script that, similar to the process outlined [here](https://github.com/aspnet/EntityFramework/wiki/Visual-Studio-Publish-Integration#what-were-doing-in-ef7-1), would run `ef migrations script -i` and use MsDeploy to execute the script during deployment?

I wouldn’t expect any official tooling support, but it would be great if there was some guidance (even just a paragraph in the docs or wiki) with a recommended approach to using migrations with Kudu deployments.

**Comment by rowanmiller** [comment]
@ryanerdmann I've opened https://github.com/aspnet/EntityFramework/issues/5207 to sort this out.

**Comment by rowanmiller** [comment]
Apply migrations during publish is now enabled and will ship in RC2... and the nasty apply migrations code in Startup.cs is being removed from the templates 🎉 🎆 💃
