### ISSUE TITLE
RevEng: Use DataAnnotations when possible in generated code

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#2712]
By default we should generate code similar how we did in EF6 for the "Code First from existing database" workflow, e.g. avoid unnecessary configuration, prefer `DataAnnotations` over fluent API, etc.

**Comment by rowanmiller** [comment]
It would be good to make it easy to swap to Fluent (like we did in EF6).

**Comment by ErikEJ** [comment]
How do you swap to fluent with EF6?

**Comment by rowanmiller** [comment]
@bricelam did you do a blog post on swapping to Fluent API? I vaguely remember you writing something that showed how to do it :smile:

**Comment by bricelam** [comment]
I think the only thing I wrote on it was an email to you. :smile: It's a simple matter of taking out [a couple where conditions in Context.cs.t4](https://github.com/bricelam/EntityFramework6/blob/master/src/EFTools/EntityDesign/CodeGeneration/Generators/GeneratedCode/DefaultCSharpContextGenerator.tt#L104) and removing [the code to write annotations in EntityType.cs.t4](https://github.com/bricelam/EntityFramework6/blob/master/src/EFTools/EntityDesign/CodeGeneration/Generators/GeneratedCode/DefaultCSharpEntityTypeGenerator.tt#L89).

**Comment by lajones** [comment]
I checked in the fix for this with commit 6adcb44 (see https://github.com/aspnet/EntityFramework/pull/2957). As it stands there is a bool flag in both templates called useAttributesOverFluentApi which controls whether we use DataAnnotations or not. But see also #2947 which will change this (exactly how it will change has not yet been planned).
