### ISSUE TITLE
RevEng: allow the user to select which tables from the database to use

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework#2751]
Reverse-Engineering at the moment assumes that you want to reverse engineer all the tables from the database. Allow the user to specify which tables they want.

**Comment by divega** [comment]
Had an initial discussion with @lajones today, we want to have this fundamental ability exposed to our command line and also APIs so that we or someone can later build UI for it. Some ideas we had on the whiteboard of what we want to support:
- Defining the set of tables by inclusion and exclusion
- Defining what gets excluded or included by exhaustive enumeration (i.e. list of tables) or pattern matching
- For command line we can support different kinds of inputs:
 - Inline
 - Text file
 - Configuration keys in the application's configuration

**Comment by lajones** [comment]
With commits d3c4001 the architecture to allow you to pass in a set of inclusions and exclusions is in. With fcfe8ef I checked in the inline command-line option which will use that architecture. However the form of that is still under discussion. So keeping open for now.

**Comment by lajones** [comment]
Updated the command-line syntax as agreed in the design meeting https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes-(October-1,-2015)#table-selection-in-reverse-engineering with PR #3356.
