### ISSUE TITLE
Group joins and ordering

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#3036]
Hunting down the last remaining failing tests in the Npgsql provider, I came across `GroupJoin_customers_orders_count`. This test executes the following LINQ:

```c#
from c in cs
join o in os on c.CustomerID equals o.CustomerID into orders
select new { cust = c, ords = orders.Count()
```

Which causes the following SQL to be sent:

```sql
SELECT "c"."CustomerID", "c"."Address", "c"."City", "c"."CompanyName", "c"."ContactName", "c"."ContactTitle", "c"."Country", "c"."Fax", "c"."Phone", "c"."PostalCode", "c"."Region", "o"."OrderID", "o"."CustomerID", "o"."EmployeeID", "o"."OrderDate"
        FROM "Customers" AS "c"
        LEFT JOIN "Orders" AS "o" ON "c"."CustomerID" = "o"."CustomerID"
```

While this looks OK, but an `ORDER BY` on `CustomerID` is missing in the SQL: in PostgreSQL the rows come back in random order, making multiple rows for the same customer arrive in totally different areas of the resultset. This makes the grouping operation in `QueryMethodProvider._GroupJoin` fail.

I'm not sure why exactly this test passes for SqlServer and Sqlite, could be because they internally maintain insertion order whereas PostgreSQL doesn't.

My initial reaction was to simply add an `order by c.CustomerID` to the LINQ. This makes the grouping work, but there's something deeper here: shouldn't every GroupJoin operation implicitly order by the parent scope's key (or rather, by the column being used to join)?

(As a complete sidenote, should this specific query be grouped in SQL since it uses count? Or is this not yet supported?)

**Comment by divega** [comment]
@roji a bit off topic but I am curious if you are running any LINQ tests on PostgreSQL that apply `Skip()` and `Take()` without an `OrderBy()`. 

My understanding is that PostgreSQL would return rows in random order as well in that case but I am not sure if the random order is stable or randomly random :smile:

FWIW, SQL Server would normally error for that kind of query but [we made specific changes](https://github.com/aspnet/EntityFramework/commit/5d5d541578fc3101729e10af8b514bce87408e41) on our SQL generation (just for SQL Server) to introduce a stable order, and I have been wondering since then whether that was a good idea.

**Comment by roji** [comment]
@divega, I'm not 100% sure but I don't think PostgreSQL returns errors for unordered queries of this sort (at least I haven't read about this anywhere). I guess it's reasonable to assume that the random order is stable (rather than randomly random, otherwise PostgreSQL is taking special steps to randomize the output!), but in any case I think it's very good practice to introduce stable ordering in the SQL that EF7 generates.

I'll test this and confirm whether it solves my issue.

**Comment by roji** [comment]
Looks good, thanks!
