### ISSUE TITLE
Commands: Start a new namespace when generating migrations for a different context

### ISSUE THREAD

**Issue by poke** [aspnet/EntityFramework#3124]
If you have multiple contexts in your project, you can create multiple migrations with the same name. For example:

    dnx ef migrations add Example -c ContextA
    dnx ef migrations add Example -c ContextB

This will result in two `<timestamp>_Example.cs` files in the `Migrations` folder. Since the generated classes are partial, this only throws an error because the class then receives two `DbContextAttributes`.

In comparison, when trying to create two migrations with the same name for a single context, the command correctly fails with an error that the name is already used by an existing migration.

Because of how the migrations are created, adding a migration should always fail if one with the same name already exists, even if it is for another context.

In the long run, it might be more useful to either prefix the migrations by the context name automatically or even move them into a subfolder/subnamespace.

**Comment by poke** [comment]
The error is there because in [`MigrationsAssembly.cs`](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Internal/MigrationsAssembly.cs#L42) the migrations that exist in the assembly are filtered by the current context, so the [`FindMigrationId`](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Internal/MigrationsAssembly.cs#L59) (used by [`MigrationScaffolder`](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/Migrations/MigrationScaffolder.cs#L66)) can only check for migrations of the current context.

**Comment by bricelam** [comment]
In general, you should put migrations for different `DbContext`s in different namespaces. We should consider proactively recommending this guideline by warning when you scaffold migrations into a namespace for a different context.

We've also talked about automatically putting migrations for the second context into their own namespace. The problem we hit was what do we name the namespace? `<root>.Migrations.<context-name>` would clash and `<root>.Migrations.<context-name>Migrations` seems too verbose. It was also weird if migrations for one context were under `Migrations` and under `Migrations.Other` for the other. We also considered "promoting" the first set of migrations to something under "Migrations" but we'd have to change file locations and class namespaces to do it right which is error-prone and probably not worth the effort.

**Comment by poke** [comment]
> In general, you should put migrations for different DbContexts in different namespaces.

That is absolutely fine with me, but as far as I’m aware, the current tooling does not offer to do that. All migrations are automatically placed into `<root>.Migrations`, even if the contexts are in different namespaces (in my case, I have one in `<root>.Models` and one in `<root>.Models.Identity`). Am I supposed to move the migrations manually into different namespaces after scaffolding them?

Maybe we could infer a better namespace for the migration from the context’s namespace. E.g. in my case, I would get `<root>.Migrations` and `<root>.Migrations.Identity`. So basically map `<root>.Models.*` to `<root>.Migrations.*`—but I guess that also requires that people put their contexts into the Models namespace.

In any case, the situation explained above should still result in an error at the command line, so you don’t find yourself having multiple conflicting files.

**Comment by rowanmiller** [comment]
Notes for triage:

> Maybe we could infer a better namespace for the migration from the context’s namespace

I like this, though perhaps just using the contexts name rather than namespace. I.e. `BlogContext` would give you `<root>.Migrations.Blog` and obviously use the same folder structure. I know we discussed this a while back and thought it wasn't optimal for the single context scenario... but I don't think it really makes that any worse (and of course you can always just move them back up if you don't want the additional nesting.

**Comment by rowanmiller** [comment]
@poke 

> In any case, the situation explained above should still result in an error at the command line, so you don’t find yourself having multiple conflicting files.

Why does this need to be invalid. You use the names when applying migrations, and in this case you have always specified which context you want to operate on.

**Comment by poke** [comment]
@rowanmiller My point is that you can easily create migrations with the same name for multiple contexts but as soon as you have a second one, you completely break the project at compile time.

**Comment by rowanmiller** [comment]
@poke only if they are in the same namespace though right? Our recommendation is to use separate namespaces... but I agree that we should make this happen by default rather than requiring you to move things.

**Comment by poke** [comment]
Yes only if they are in the same namespace, but as I said above, there is no way to adjust the namespace other than moving the types manually afterwards. So creating a migration should fail if there is already a migration in the target namespace (i.e. `<root>.Migrations` now, or whatever generated namespace in the future) already contains a migration with the same name. The check should not go by the database context alone but also respect the location where the migration would be created at.

**Comment by rowanmiller** [comment]
**Triage:** We will continue to generate migrations for the first context in `<root>.Migrations` but if you start adding migrations for a second context (i.e. if there are migrations for a different context in the namespace we are going to generate to) then we will create a sub-namespace/folder for the second context for you. That way you don't have to move files around and there are no type name conflicts.

We can't just use the context name, because then you get type name and namespace name conflicts. If the context name ends in `Context` then we will just remove it and use the remaining name. Otherwise we will come up with something based on the context name that shouldn't conflict (possibly using underscores).

Once we have this working it will be easy to tweak the rules around how we choose the sub-namespace name etc. based on app building and feedback.
