### ISSUE TITLE
Query: Implement query tracking behavior decisions

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#3134]
See https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes---August-6,-2015

**Comment by anpete** [comment]
See comments on #3080

**Comment by divega** [comment]
We need to consider the behavior of the Load() method on [EntityFrameworkQueryableExtensions](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/Extensions/EntityFrameworkQueryableExtensions.cs). It would probably make sense for it to always track. We could also consider removing it for now.

**Comment by davidroth** [comment]
@divega I would not be happy if you would remove ```Load()```.

It is a nice option to conditionally load related collections into a graph, without the overhead of ```ToList()``` and with more power than ```Include()```.
We use it often because ```Include(x => x.SomeRelatedCollection)``` is often too limited (e.x. no where conditions can be applied) and it is too slow in EF6 because of the Cartesian product (Something which should not be a problem anymore in EF7).

So i think ```Load()``` should either always track the elements or throw an exception if the context is configured for notracking. But please don't remove it ;)

**Comment by rowanmiller** [comment]
**Triage:** Agreed that `Load()` can always imply tracking
