### ISSUE TITLE
Clean up TFMs and #ifs

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#3517]
We need to follow up on a few issues after 7e0ba479a2cc1242ff7d6688687a740bd8a606f4:

- [ ] 1. UWP stopped working (although it was supposed to work with dotnet5.4)
- [x] 2. We need to figure out if we still need to support net45. That would require changes on dependencies.
- [x] 3. Related to (2), the automatic script created a funny `#if NET451 || NET451`
- [x] 4. In general it would be good to do a pass over all #ifs to make sure they still make sense

**Comment by natemcmaster** [comment]
Our code falls down in 2 places due to generations and our uses of `#if`:

1. Throwing for ambient transactions
If using `net451` or `net46`, this will behave as expected. But if the user switches to `dotnet5.4`, then ambient transactions will not throw.

2. DbSet implementation of IListSource.
This will surface as a compiler error because IListSource does not exist in the .NET Core contract.

**Comment by natemcmaster** [comment]
Futhermore, to support `net45`, we need all "Microsoft.Extensions.*" packages to downgrade to net45. This could be problematic if any depend on API changes between `net451` and `net45`. I will investigate more...

**Comment by natemcmaster** [comment]
@divega how bad do we need net45? Basically, we'd need to rebase everything in aspnet down to net45. 

cc @davidfowl

**Comment by divega** [comment]
I do remember we decided that long time ago but I can't remember if there was any tecnical reason besides being able to use EF in more scenarios. So it is hard for me to answer how bad we need it now.

Is it possible that Mono requird net45? 

Cc @rowanmiller @ajcvickers

**Comment by ErikEJ** [comment]
@natemcmaster I can easily upgrade to net451 - I think there were some ADO.NET improvements, that you needed in that one anyway: https://msdn.microsoft.com/en-us/library/system.data.common.dbparameter(v=vs.110).aspx

**Comment by rowanmiller** [comment]
I don't think we required net45 for Mono... I think we just enabled it because it was minimal work to do so (the non-relational parts of the stack have always supported net45, and it was just some minimal changes in the relational packages).

From my perspective, net451 is fine (unless we find something that breaks in Mono etc.)

**Comment by divega** [comment]
We discussed this and we'll stick to net451 for RC1. If any issue arise we can consider having net45 again in RTM.

@erikej ADO.NET providers built for 4.5 should still work without changes because `Precision` and `Scale` were added in `DbParameter` with an implementation that invokes the pre-existing interfaces.

**Comment by ErikEJ** [comment]
@divega fine, but my question is: should the sqlce EF provider require .net 4,5 or .net 4,5,1?

**Comment by divega** [comment]
I believe it will need to be 4.5.1.

**Comment by natemcmaster** [comment]
Fixed UWP installation with #3558
