### ISSUE TITLE
Make it easy to create a provider configured ModelBuilder

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#3529]
One scenario we want to support is external model creation via ModelBuilder. However, it is currently difficult to get a ModelBuilder instance that has been configured with a provider specific convention set.

cc @sebastienros

**Comment by rowanmiller** [comment]
Discussed in triage and decided we should have ModelBuilder factories so that folks don't need to worry about conventions etc. (especially since conventions are 'internal' for the first release).

Folks can just create one up like this (note this is a static `Create()` method on the factory rather than a default ctor to get a factory since having a default ctor doesn't play well with DI):

```
var builder = SqlServerModelBuilderFactory.Create()
```

Alternatively, if you want it to get all it's services from DI then we'll register one that you can just resolve... then you will get the same logger, etc. that is registered in DI (plus if you have overridden the type mapper etc. then you will also get those services).

```
sp.AddEntityFramework()
  .AddSqlCompact()
  .AddNpgSql()
  .AddSqlServer();

var builder = sp.GetService<ISqlServerModelBuilderFactory>().Create();
```

**Comment by rowanmiller** [comment]
BTW when we do this we should consider making convention sets internal too. I know providers might use them... but that is ok, it just means they aren't guaranteed to be stable between releases.
