### ISSUE TITLE
Remove Roslyn Depencency

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#3602]
As far as I know, the only thing it's still used for is sanitizing identifiers...

**Comment by rowanmiller** [comment]
@bricelam what is the value of removing this? Will we just end up replicating the logic to sanitize?

**Comment by bricelam** [comment]
Less packages pulled into the user's project, less chance of conflicts with other packages. Yes, we'd just reimplement it locally.

**Comment by lajones** [comment]
We have dependencies on `Microsoft.CodeAnalysis.*` in `Commands`, `Relational.Design` and several test projects. In the src projects it is always a dependency on `SyntaxFacts` which we use to determine invalid characters (both at start and in the middle) of an identifier, whether an identifier as a whole is valid, whether an identifier is a keyword etc.

In the test projects it's more complicated - in particular the `MicrosoftSqlServer.FunctionalTests` project has a large dependency on Roslyn because the tests compile the resulting code in order to check that it compiles successfully.

Also note: when considering this there is a suggestion in #3532 to do the opposite i.e. to stop using `CSharpUtilities` altogether and instead focus only on `Microsoft.CodeAnalysis.*`.

**Comment by bricelam** [comment]
To clarify, I just mean removing the dependency from the product (i.e. src), not tests. Compiling code is necessary for the functional tests.

**Comment by ErikEJ** [comment]
All those frameworks will be lost in time like tears in rain

Yay!
