### ISSUE TITLE
Query: Ensure no SQL injection possible when using InExpression

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#3685]

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

**Comment by anpete** [comment]
Verified that we have a test for this.
