### ISSUE TITLE
Value cannot be null. Parameter name: navigation

### ISSUE THREAD

**Issue by HalidCisse** [aspnet/EntityFramework#3805]
I upgraded from EF6 SQLServer to EF7 SQLite -7-rc1-final.
Full .NET WPF
The context is not in the startup assembly.

Stack trace: https://gist.github.com/HalidCisse/02de3081aa6faafaac70

**Comment by rowanmiller** [comment]
@HalidCisse can you share the code for your context and model.

**Comment by HalidCisse** [comment]
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=ef7.ea");
        }

**Comment by rowanmiller** [comment]
We'll need the full model since this looks like a bug that will manifest when you have a particular pattern in your model.

**Comment by HalidCisse** [comment]
Its around 50 models

**Comment by rowanmiller** [comment]
Yep, I was expecting it would be a decent size model because there must be one particular pattern somewhere that is causing this issue. Adding me to TFS sounds fine, or I can give you my email if you'd rather just zip it up and send it thru?

~Rowan

**Comment by nocommonsense** [comment]
Hi @rowanmiller ,

I'm having similar issues with my project also. Would be keen to know what the cause of this is :)

Thanks,
Ian

**Comment by nocommonsense** [comment]
@rowanmiller ,

I've managed to rectify the issue I was having - I had a stray Foreign Key attribute against a property  in one of my models following moving over to Fluent API, removing this has fixed the error. 

Ian.

**Comment by GorelH** [comment]
@rowanmiller here is my email halidoucse@gmail.Com

**Comment by HalidCisse** [comment]
@rowanmiller here is my email halidoucse@gmail.Com for the zip

**Comment by jofran73** [comment]
I get the "value cannot be null. Parameter name: navigation"-exception with the following model when running migrations. The setup is a base class that has a navigation property to a subclass. The exception occurs only when the subclass implements the collection-navigation property.

```
public class Customer
{
    public int Id { get; set; }

    public int? SpecialCustomerId { get; set; }
    public SpecialCustomer SpecialCustomer { get; set; }
}

public class SpecialCustomer : Customer
{
    public string SomethingSpecial { get; set; }

    public List<Customer> Customers { get; set; } // causes exception
}

public class CustomerDbContext : DbContext
{
    public DbSet<Customer> Customer { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(e =>
        {
            e.HasKey(m => m.Id);

            e.HasOne<SpecialCustomer>(m => m.SpecialCustomer)
            .WithMany( m => m.Customers) // -- causes Exception
            .HasForeignKey(m => m.SpecialCustomerId)
            .IsRequired(false);
        });

        modelBuilder.Entity<SpecialCustomer>(e =>
        {
        });

        base.OnModelCreating(modelBuilder);
    }
}
```

**Comment by smitpatel** [comment]
@jofran73 - Thanks for the repro code.
The exception - navigation being null happens with rc1 bits but no longer reproduces in latest bits. Though above code throws NullRef exception with latest code.
The issue here is - When the foreign key is replaced, we run appropriate conventions. Though some of the convention can remove the present foreign key and after that we try to run convention on such removed foreign key. So some of the components of the foreign key are null (due to being removed from model) hence throws NRE.
Till rc1 the navigations were stored on the entity type so removed foreign key marks the appropriate navigations in the FK as null which throws parameter navigation is null exception. This no longer reproduces because now foreign key stores the navigations.
The another null ref is occurring in key convention because the foreign key properties are removed from the model.
The fix is to run the convention only if the current foreign key is part of the model.
