### ISSUE TITLE
Better experience/support for migrations in class library

### ISSUE THREAD

**Issue by f0rt** [aspnet/EntityFramework#3879]
Hi team,
I'm trying to create a library project(Data) that contains DBContext consumed by ASP.NET 5 application and Console Application (package). I have this definitions in my project.json:
"commands": {
    "ef": "EntityFramework.Commands"
  },
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "SonarFish.Configuration": "1.0.0-*",
    "System.Runtime.Serialization.Primitives": "4.1.0-beta-23516"
  }

When I run "dnx ef migrations add m1" on my Data project I'm getting the error: 
"System.InvalidOperationException: No database providers are configured. Configure a database provider by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services."

I've added the following implementation to OnConfiguring but the error is still the same:
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
         optionsBuilder.UseSqlServer("<ConnectionString>");
         base.OnConfiguring(optionsBuilder);
      }

What am I doing wrong?
What is the best way to implement if I have 2 projects that have to consume a single DBContext?

Thanks in advance! :)

**Comment by stevejgordon** [comment]
I managed to get this working although I am still facing issues after trying to change to the recommended dotnet5.4 framework naming. What frameworks are you targeting in project.json?

Have you added anything in your Startup.cs to handle setting up ef? I copied in the appsettings file from an MVC6 project (which contains the connection string) as well as adding the following in my startup.cs

    public class Startup
    {
        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json");

            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; set; }
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
        }

        public void Configure(IApplicationBuilder app)
        {
        }
    }

After this I was able to use the commands correctly to add a migration and update the database.

**Comment by f0rt** [comment]
Thanks for the reply @stevejgordon.
 
Q: What frameworks are you targeting in project.json?
A: dnxcore50. Is this the correct string or some of the VS templates are not updated?

Q: Have you added anything in your Startup.cs to handle setting up ef?
A: As I said I'm trying to create a library project to handle all DB operations. Should I add appsettings.json and Startup.cs to it?

**Comment by stevejgordon** [comment]
I'd seen that the new RC1 template for a Class Library (Package) defaults to dotnet5.4 which I understood throuhg limited reading was the new preferred naming to target the core platform. However I have just opened an issue on this since the EF libraries seemed not to like this. I'm currently targeting dnx46 and dnxcore50. So you should be okay there.

On the startup.cs front I understand that this is needed in the class library project also if you want to use the EF commands. The reason is that something needs to bootstrap the services in order to be able to run commands to the database. I suspect this isn't needed when you have a web project referencing the data class library since the startup there will bootstrap the required services and configuration.However you will need it for ef commands.

That's at least what I'e understood so far after a few days playing with it all. Certainly for now my DAL has an appsettings and startup.cs added in the root. App settings is only needed if you want to load the connection string from a settings file. You could of course hard code that directly in the startup.cs

**Comment by f0rt** [comment]
Works like a charm!! Thank you again for your efforts. :)

**Comment by stevejgordon** [comment]
You're welcome.

**Comment by bricelam** [comment]
Thoughts I've had on how to help this:
- Override migrations assembly to the target project at design-time
- Warn if it's different from the configured migrations assembly

**Comment by ryancole** [comment]
I tried following the suggestion in #3840, by @bricelam, but I don't think it's working how I expected. I've got the same configuration as the creator of #3840, with my `DbContext` defined in a seperate project within the same solution as my ASP.NET project. I adjusted the code, in the ASP.NET project's `Startup.cs` file, to call `MigrationsAssembly` in the `ConfigureServices` method. Here's that code ...

```csharp
public void ConfigureServices(IServiceCollection services)
{
    var connection = @"Server=(localdb)\mssqllocaldb;Database=League;Trusted_Connection=True;";

    // register mvc server
    services.AddMvc();

    // register entity framework services
    services.AddEntityFramework()
            .AddSqlServer()
            .AddDbContext<LeagueContext>(options =>
            {
                options.UseSqlServer(connection)
                       .MigrationsAssembly("League.Data");
            });
}
```

The assembly that has the `DbContext` is `League.Data`. This seems to be finding the assembly, because if I change it to something that doesn't exist, like `League.Datafoo`, it throws an error, but does not throw an error when using the correct name.

So, with this setup, if I change directories into the ASP.NET project's directory, here's the output of the various dnx ef commands ...

```
C:\Users\Ryan\Projects\League\League.Web>dnx ef dbcontext list
League.Data.Context.LeagueContext

C:\Users\Ryan\Projects\League\League.Web>dnx ef migrations add First
Done. To undo this action, use 'ef migrations remove'

C:\Users\Ryan\Projects\League\League.Web>dnx ef migrations list
No migrations were found
```

**Comment by bricelam** [comment]
MigrationsAssembly Should point to the one with the Migration classes in it. That's League.Web in your usage above.

**Comment by ryancole** [comment]
Ah, that does it! Makes sense. :+1: Thanks.

**Comment by paulhanssen** [comment]
Hi,

I have a similar situation to this but with the class library (containing "League.Data.Context.LeagueContext") is a ASP.Net 5 Class Library (Package) that I import as a package using nuget (it's in it's own solution as we use it in multiple API projects).

I then try to access information about migrations from the ASP.Net 5 MVC 6 project Package Manager Console. I've referenced the assembly as written above.

The error I receive is (cast to the above example):
```
PM> dnx ef dbcontext list 
League.Data.Context.LeagueContext
PM> dnx ef migrations list 
System.InvalidOperationException: Unable to resolve service for type 'System.Action`1[Microsoft.Data.Entity.DbContextOptionsBuilder]' while attempting to activate 'League.Data.Context.LeagueContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Data.Entity.Internal.DbContextActivator.CreateInstance[TContext](IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Data.Entity.Design.DbContextOperations.<>c__DisplayClass9_2.<FindContextTypes>b__6()
   at Microsoft.Data.Entity.Design.DbContextOperations.CreateContext(String contextType)
   at Microsoft.Data.Entity.Design.MigrationsOperations.GetMigrations(String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass8_0.<ListMigrations>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
Unable to resolve service for type 'System.Action`1[Microsoft.Data.Entity.DbContextOptionsBuilder]' while attempting to activate 'League.Data.Context.LeagueContext'.
```
I can see the "Initial" migrations class in the Solution Explorer, but not the Snapshot class (as it's by default internal).

Any idea what I doing anything wrong?

I'm using the nightly builds:
        "EntityFramework.Core": "7.0.0-rc2-16485",
        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-16485",
        "EntityFramework.Relational": "7.0.0-rc2-16485",

Cheers
