### ISSUE TITLE
Prevent DbContext.Set<T>() from creating sets for types not in the model

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#4301]
Currently we create sets for any type... but they fail ungracefully if used to do anything (NullReferenceException etc.). We should just throw in the Set<T> method if T is not in the model.

**Comment by ajcvickers** [comment]
@rowanmiller Note that the fix for this will throw when the Set method is called with an unmapped type, but will not prevent the application from putting DbSet properties of unmapped types in their context. I expect these will still null ref in some way. Is this okay?

If we decide to also do a check for DbSet properties in the context, the check cannot happen at construction time since this would require model initialization which would kill perf for creating unused context instances. So the check would need to be done when the set is used, or for all DbSet properties at the time of full context initialization.

**Comment by rowanmiller** [comment]
@ajcvickers yeah I think that is fine... putting a DbSet, then ignoring the type, then trying to use the DbSet is probably not very common :smile:
