### ISSUE TITLE
Investigate Sql statements ordering in tests

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#4458]
For tests
`Where_nav_prop_reference_optional1_via_DefaultIfEmpty` & `Where_nav_prop_reference_optional2_via_DefaultIfEmpty`
The generated SQL has 2 statements. Test on coreclr and full desktop has different ordering of the SQL statements. Disabled SQL assertion till investigated.

**Comment by rowanmiller** [comment]
If ordering doesn't matter then we should make the test pass with either order

**Comment by maumar** [comment]
This is due to Enumerable.Join having different implementation between coreclr and net451. Filed a bug on corefx team to track this: https://github.com/dotnet/corefx/issues/6477

**Comment by JonHanna** [comment]
Hi. In case anyone isn't following the corefx issue, I'm arguing there we should keep the difference (it allows us to short-circuit on some cases where the results of the join are empty). It seems that the issue it caused you was purely with testing rather than EF itself, and as such #4611 is all you need.

If someone can think of a reason why I'm wrong on that, please visit https://github.com/dotnet/corefx/issues/6477.

**Comment by maumar** [comment]
this is due to optimization done in corefx - source collections are executed in different order now to allow some short circuiting. The discrepancy is by design and we just need to be mindful in out tests.
