### ISSUE TITLE
Migrations finds multiple DbContext when the containing assembly defines multiple localized resx resources

### ISSUE THREAD

**Issue by ghost** [aspnet/EntityFramework#4606]

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing? Can you provide details of the error you are seeing (message and stack trace)?

**Comment by pepevc** [comment]
This is what happened to me:

1. Create a Class Library project.
2. Define a DbContext.
3. Add a Resources.resx file.
4. Add a Resources.de.resx file.
5. Compile. The class library should produce a satellite assembly output for the "de" language.
6. Reference the DbContext from other project.
7. Try to generate the database with the ef command.
8. The command will fail indicating that there are multiple DbContexts.

Hope it helps.

**Comment by bricelam** [comment]
I am not able to repro this on RC2. I suspect it was fixed with the transition to the .NET Core CLI.
