### ISSUE TITLE
Projection of included entity doesn't work with Skip Take

### ISSUE THREAD

**Issue by gdoron** [aspnet/EntityFramework#4637]
Hi,

I saw you already have multiple `Take` bugs reported, but couldn't find my bug among them.
I'm trying to implement paging with projection of included entity but it fails with an odd exception:

> System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryable`1..ctor(IAsyncQueryProvider provider)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor._CreateEntityQueryable[TResult](IAsyncQueryProvider entityQueryProvider)

The query:

```
var results = await _context.Posts.Include(x=> x.User)
                .Where(x => x.ForumId == forumId && x.ReplyToPostId == null)
                .Skip(pageSize*page)
                .Take(pageSize)
                .Select(x=> new
                                {
                                    x.User.UserName
                                })
                .ToListAsync();
```

And the model which you probably already know by heart... :smile:

    public class Post
    {
        public int Id { get; set; }

        public string Title { get; set; }
        public string Body { get; set; }

        public DateTime PublishDate { get; set; }

        public DateTime? LastChangedDate { get; set; }

        public bool IsModified { get; set; }

        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public int ForumId { get; set; }

        public virtual Forum Forum { get; set; }

        public int? ReplyToPostId { get; set; }

        public Post ReplyToPost { get; set; }

        public bool IsDeleted { get; set; }
        public bool IsImportantReply { get; set; }

        public virtual List<Post> Replies { get; set; }

        public PostType PostType { get; set; }

        public bool IsLocked { get; set; }

        public string LockingUserId { get; set; }
        public ApplicationUser LockingUser { get; set; }
        public string LockReason { get; set; }
        public int Score { get; set; }

        public List<Vote> Votes { get; set; }
    }

If I'm removing the Skip-Take or removing  the Username  from the Select it works, when they are combined it doesn't.

The entire project is hosted publicly on Github if you need to see the entire code and fiddle with it
https://github.com/gdoron/Forums/blob/Projection/src/Forums/Controllers/Api/ApiPostsController.cs#L35

Thanks

**Comment by rowanmiller** [comment]
@mikary can you check if this is fixed

**Comment by mikary** [comment]
Ran the provided samples against `Microsoft.EntityFrameworkCore.SqlServer 1.0.0-rc2-final`. No exceptions were thrown and the results appear to be correct.

Adding tests to cover regressions in #5436

**Comment by mdmoura** [comment]
Is this working in RC2? I tried a Skip / Take before a projection and I get an exception. If I move it to after the projection then it works fine ...

**Comment by mikary** [comment]
@mdmoura I verified the exception was not being thrown for this issue on RC2, but if you are still seeing problems there may still be an issue. Could you provide more details on the error you are seeing (exception message, code for the query and model)?

**Comment by mdmoura** [comment]
@mikary: The models are:

    public class Job {

      public Int32 Id { get; set; }
      public String CountryCode { get; set; }
      public String City { get; set; }
      public Boolean IsEnabled { get; set; }
      public virtual Country Country { get; set; }
    } 

    public class Country {
      public String Code { get; set; }
      public String Name { get; set; }
      public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
    }

The query is:

    var result = await _context.Jobs
       .OrderBy(x => x.Start)
       .Include(x => x.Country)            
       .Where(x => x.IsEnabled)
         .Skip(0).Take(10)
         .Select(x =>
             new {
                Id = x.Id,
                Country = new {
                  Code = x.Country.Code,
                  Name = x.Country.Name
                }
              })            
            .ToListAsync();

And I get the error:

The given expression 'new <>f__AnonymousType1`2(Id = [x].Id, Country = new <>f__AnonymousType2`2(Code = Property([x], "CountryCode"), Name = [x.Country].Name))' does not contain the searched expression '[x]' in a nested NewExpression with member assignments or a MemberBindingExpression.
Parameter name: fullExpression
   at Remotion.Linq.Clauses.ExpressionVisitors.AccessorFindingExpressionVisitor.FindAccessorLambda(Expression searchedExpression, Expression fullExpression, ParameterExpression inputParameter)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

The error can be removed in a few ways like:
1. Placing the OrderBy after the Include (By design? Bug?)
2. Remove the Country projection.

Does this help?

**Comment by maumar** [comment]
@mdmoura this looks like a separate issue. I have filed https://github.com/aspnet/EntityFramework/issues/5612

**Comment by mdmoura** [comment]
@maumar: yes, but I also think there is a bug here in relation to Skip Take after and before the projection ... I just haven't been able to isolate it yet because I have quite a large model. I will post here more information if that is the case.

**Comment by maumar** [comment]
@mdmoura sounds good. The case you provided is most likely related to the complex projection itself (as the exception says, we are trying to find query source [x] in the projection, and we failed to do it, even though its clearly there)
