### ISSUE TITLE
ModelBuilder fails depending on properties names

### ISSUE THREAD

**Issue by frbar** [aspnet/EntityFramework#4682]
`Add-Migration` fails with below classes.

> The navigation 'N' on entity type 'Console.MN' has not been added to the model, or ignored, or target entityType ignored.

If I rename `N` property with `M` (or any name starting with letter < `M`) in `MN` class, migration runs fine.

```
using Microsoft.Data.Entity;
using System;
using System.Collections.Generic;

namespace Console
{
    public class MT
    {
        public Guid Id { get; set; }
        public MN RN { get; set; }
    }

    public class MN
    {
        public Guid Id { get; set; }

        public MN N { get; set; }

        public MN PN { get; set; }

        public IList<MNL> MNLs { get; set; }
    }

    public class MNL
    {
        public Guid PNId { get; set; }

        public Guid CNId { get; set; }

        public MN PN { get; set; }

        public MN CN { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<MT> MTs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=MyDatabase;Trusted_Connection=True;");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {

        }
    }  
}
```

**Comment by smitpatel** [comment]
Which version of EF are you using?

**Comment by frbar** [comment]
rc-1 (-Pre when doing install-package).
________________________________
De : Smit Patel<mailto:notifications@github.com>
Envoyé : ‎02/‎03/‎2016 17:55
À : aspnet/EntityFramework<mailto:EntityFramework@noreply.github.com>
Cc : BARONNET, François<mailto:Francois.BARONNET@sage.com>
Objet : Re: [EntityFramework] Migration fails depending on properties names (#4682)


Which version of EF are you using?

**Comment by smitpatel** [comment]
This still reproduces in nightly build. Based on property name there are different behavior occurring.

**Comment by smitpatel** [comment]
@frbar - Thank you reporting this bug.
Issue: When we encountered multiple relationship candidates, we were falling out of the loop if we find ambiguous candidate. Therefore rest of candidates were not being processed to build relationships. The issue did not surfaced so far because such missing relationships are found by the relationship discovery convention running on the other side. Which fails for self-ref relationships.
In this case, navigation `MNLs` is found first which is ambiguous since type `MNL` has 2 inverse navigations. This causes the second relationship candidate with navigations `PN` & `N` not to be build relationship. For either of those navigation has a name which comes before `MNLs` alphabetically then that relationship candidate will come first and build relationship.
