### ISSUE TITLE
composite key in model causing invalid SQL

### ISSUE THREAD

**Issue by dshamim** [aspnet/EntityFramework#5047]
if in modelBuilder there is a composite key present and the object is in multiple relatinships
e.g. A contains Many B, B contains many C with fully defined relationships 
then fetching A with dependents results in invalid column ID in query, if relationship to C is commented out, it works fine

`modelBuilder.Entity<A>(entity=> {        
        entity.HasKey(e => new{ e.EventId, e.EventCloseDate});        
    });`

more detail logged here [http://stackoverflow.com/questions/36586487/entity-framework-7-generating-invalid-column-name/36587278](http://stackoverflow.com/questions/36586487/entity-framework-7-generating-invalid-column-name/36587278)

**Comment by smitpatel** [comment]
Using model from stackoverflow question, while I am trying to generate model, I am hitting following exception:
`The key {'EventId1'} contains properties in shadow state and is referenced by a relationship from 'Event.Sessions' to 'Session.Event'. Configure a non-shadow principal key for this relationship.`
The conflicting lines in the model causing this error are:
````c#
modelBuilder.Entity<Event>()
        .HasMany(s => s.Sessions)
        .WithOne(e => e.Event).HasForeignKey(s => s.EventId);
modelBuilder.Entity<Event>().HasKey(e => new{ e.EventId, e.EventCloseDate});
````
First line of code defines one to many relationship between sessions and event which uses `EventId` (in Session class as foreign key property. By default this FK targets the PK of principal type - `Event` which is `EventId` by convention. When second line tries to set composite PK on `Event` class, the relationship defined before cannot use that PK any longer since relationship has only 1 property as FK. Therefore conventions will create a shadow property from the user-configured FK property and define key on shadow property to be used as principal key for relationship. Since `EventId` property already exists, the shadow property created has name `EventId1`. Since shadow keys are not allowed in the model, above exception is thrown during model validation phase. As exception message says, user is trying to set single property FK targeting principal type with composite key therefore user has to specify the principal key explicitly.

It seems that RC1 packages was not making such checks therefore the generated query contained `EventId1` column.
Since above 2 statements in model building is causing this issue to arise, removing either of those (not configuring relationship explicitly or not defining composite PK) resolves the issue. Or other work-around would be define principal key to use in explicit relationship configuration.

**Comment by dshamim** [comment]
I worked around by removing the composite key (and using primary only) -
issue arose because i used scaffolding to generate the models and it
inherited the properties form the existing table

**Comment by smitpatel** [comment]
@rowanmiller - Is there anything actionable from our side here?

**Comment by rowanmiller** [comment]
Don't think so, if you are happy we understand it and there is nothing to change then feel free to close 😄
