### ISSUE TITLE
Migrations: Scaffold MaxLength

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/EntityFramework#5223]
When I apply

```
[StringLength(60, MinimumLength = 3)] //nvarchar(MAX) to nvarchar(60)
```

to my existing model, EF doesn't pick up this change.

To repro: 

1. Create a model with string and no DataAnnotations. 
2. add migrations/update
3. apply ``[StringLength(60)0``

EF doesn't detect the change.

#5224 <-- NOT NULL is detected but not enforced

**Comment by smitpatel** [comment]
Tested this with nightly builds
The generated migration file does not have string length changes
```c#
    public partial class StringLength : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Entity",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Entity",
                nullable: true);
        }
    }
```
On the other hand model snapshot is updated to account for change in length.
```
                    b.Property<string>("Name")
                        .HasAnnotation("MaxLength", 50);
```
Also the generated migration script has alter column statement.
```
ALTER TABLE [Entity] ALTER COLUMN [Name] nvarchar(50);
GO
INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20160429195756_StringLength', N'1.0.0-rc3-20747');
```

**Comment by rowanmiller** [comment]
Interesting... I guess we are reading the length information out of the target model snapshot... we should stop doing that 😄

**Comment by rowanmiller** [comment]
@Rick-Anderson this means that everything should work... but it's obviously super confusing that the length isn't in the generated code. We'll keep this open to address that, but it shouldn't block you.

**Comment by Rick-Anderson** [comment]
@rowanmiller  it's not blocking, I just thought you might want to know. I've finished all the scaffolding and have everything working with RC2. I did open a bunch of scaffold bugs.

**Comment by rowanmiller** [comment]
We'll discuss when @bricelam is back

**Comment by rmja** [comment]
Could this be related to #4146?

**Comment by rmja** [comment]
@rowanmiller, @bricelam  I have looked into this and the problem seems to be that the `MigrationsAnnotations.For(target)` in [this line](https://github.com/aspnet/EntityFramework/blob/a1a9e2c65551b41d4d121c8c9e6a7b3ebb9fdb54/src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L347) returns an empty enumerable as the [provider implementation](https://github.com/aspnet/EntityFramework/blob/b8555657a47a2af21f725cba50ff07124a8ec79a/src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs) does not include the max length:

```
public override IEnumerable<IAnnotation> For(IProperty property)
        {
            if (property.SqlServer().ValueGenerationStrategy == SqlServerValueGenerationStrategy.IdentityColumn)
            {
                yield return new Annotation(
                    SqlServerFullAnnotationNames.Instance.ValueGenerationStrategy,
                    SqlServerValueGenerationStrategy.IdentityColumn);
            }
        }
```

Maybe the correct thing would be to `yeild` the [core annotations](https://github.com/aspnet/EntityFramework/blob/21fdcf99d8aa00defb03d05e6c883d4df3de79fc/src/Microsoft.EntityFrameworkCore/Metadata/Internal/CoreAnnotationNames.cs) in [the default implementation](https://github.com/aspnet/EntityFramework/blob/21fdcf99d8aa00defb03d05e6c883d4df3de79fc/src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsAnnotationProvider.cs) and then iterate over them in the provider specific versions?

To allow custom annotations to "flow through", is the recommended way then to override the `For()` methods, include the new whitelisted annotations, and then replace the `SqlServerMigrationsAnnotationProvider` when setting up DI?

**Comment by rmja** [comment]
... and while you are at it, In `MigrationsModelDiffer`, could you insert `CopyAnnotations(MigrationsAnnotations.For(target), operation);` right after the creation of the `DropTableOperation()` [here](https://github.com/aspnet/EntityFramework/blob/a1a9e2c65551b41d4d121c8c9e6a7b3ebb9fdb54/src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L375) :-) I need it to control whether a table should be dropped or not.

**Comment by bricelam** [comment]
@rowanmiller said:
> Interesting... I guess we are reading the length information out of the target model snapshot... we should stop doing that 😄

Correct. The [column builder API](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational/Migrations/Operations/Builders/ColumnsBuilder.cs#L20-L26) does not include any facets. Instead, the property (or just its CLR type) is passed to the provider's type mapper where it decides what metadata to look at.

**Comment by rowanmiller** [comment]
Check that hard coded data types are also written to the scaffolded migration

**Comment by bricelam** [comment]
We decided to add `maxLength`, `unicode` & `timestamp` to the Migrations APIs.

**Comment by Rick-Anderson** [comment]
@bricelam will that make it with the RTM preview tooling ?

**Comment by bricelam** [comment]
@Rick-Anderson Yes, a PR is out for review now.
