### ISSUE TITLE
SQLite and UWP , UseWinsqlite3

### ISSUE THREAD

**Issue by subzero1001** [aspnet/EntityFramework#5325]
Does anybody knows why i get error using this namespace "UseWinsqlite3"? 

I have already installed Entity Framework Commands,Entity Framework SQL and SQLite for Universal Windows Platform  packages .

`protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseWinsqlite3("Filename=Sensors.database");
        }
`

Currently working on Visual Studio 2015 ( UWP )

**Comment by smitpatel** [comment]
There is not `UserWinsqlite3` method in EF Core.
You can find more info about how to use EF in UWP here http://ef.readthedocs.io/en/latest/platforms/uwp/getting-started.html

**Comment by divega** [comment]
There is actually `SqliteEngine.UseWinSqlite3()` which you should call early in your app if you want us to use the winsqlite3.dll library that is included in Windows instead of any other version of `sqlite3.dll`. Note that this is separate method from `optionsBuilder.UseSqlite(connectionString)` which you should call to configure your `DbContext` to use the SQLite provider. 

I guess the UWP getting started documentation should mention this.

@natemcmaster @bricelam I haven't though about the fact that `UseSqlite()` and `UseWinSqlite3()` could be confused in this way, but I believe it is interesting. I wish we could actually make it work the way the user expected it work :smile:

**Comment by ErikEJ** [comment]
More wrong code in the Windows App Team blog post 


protected override void OnConfiguring(DatabaseContextOptionsBuilder optionsBuilder) 

        { 
            optionsBuilder.UseWinsqlite3("Filename=Sensors.database"); 
        } 

https://blogs.windows.com/buildingapps/2016/05/03/data-access-in-universal-windows-platform-uwp-apps/
