### ISSUE TITLE
Entity Framework and .Text

### ISSUE THREAD

**Issue by subzero1001** [aspnet/EntityFramework#5342]
0
down vote
favorite
	

Does anyone know why I get an error in the following code ?

```
Employee objEmp = new Employee();
objEmp.HREmpId = txtHREmpId.Text;
```

Does not contain definition for 'Text' .Maybe it is an older Entity Framework version .

Currently working on Visual Studio 2015 , ASP.NET Web Application

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing?
