### ISSUE TITLE
modelBuilder.Entity<AnEntity>(e => { }) can cause StackOverflowException in some cases

### ISSUE THREAD

**Issue by AlexBilonog** [aspnet/EntityFramework#5350]
I use EntityFrameworkCore version: 1.0.0-rc3-20831, .Net Framework: 4.6, AspNet.Mvc: 5.2.3

I cannot provide certain steps to reproduce. But can point at some conditions. I have about 100 entities. And executing this code causes StackOverflowException (empty stack trace):

`modelBuilder.Entity<AnyEntity>(entity => { /* any code or empty */ })`

This bug is always reproducible on IIS Express, but on Local IIS is reproducible only in rare cases.

I found out that this bug appears only when I uncomment some navigation property in entity, but I cannot track which one nav prop causes this bug (because have large amount of entities).

EXP: If something wrong with my model (maybe some circular referencing?), could you provide more clear exception message. Without this message I can spend much time looking for 'what is wrong with my model'

EXP: Why this is reproducible only with some conditions (or not always). Seems as a bug in model builder algorithm.

By the way: in my previous version of EFCore (January 2016 (don't remember some rc2)) this bug did not exist.

Thanks in advance.

**Comment by rowanmiller** [comment]
@AlexBilonog can you share the stack trace from the exception to help us isolate the issue?

**Comment by rowanmiller** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by AlexBilonog** [comment]
Sorry for late. As I told the stack trace on StackOverflowException is empty.
But I created a test project for you (console application attached). It has 105 entities. By running this app you can see that after invoking:

`modelBuilder.Entity<Table01>(entity => { /* any code or empty */ })`

the stack size is decreased by 30% (as I know default console application stack size is 1 MB). That's why IIS Express or rarely Local IIS fails with StackOverflowException. Because default stack size is 256 KB for 32-bit ASP.NET apps.

In TheContext.cs file in OnModelCreating method you can select different options for testing.

Сorrect me if I'm wrong.
[Console3.zip](https://github.com/aspnet/EntityFramework/files/279987/Console3.zip)

**Comment by divega** [comment]
Reactivating because we now have a repro. Thanks @AlexBilonog!

**Comment by divega** [comment]
Triage: This is probably post-RTM. Some notes from a conversation with @AndriySvyryd about this (feel free to correct any inaccuracies):

Currently because of how our model builder logic works (e.g. certain changes in the model requires re-applying conventions) we have areas in which there is recursion and the depth of the stack grows linearly with the number of entities in the model. There are two approaches we believe we can apply to improve on this:

1. Mitigate it by reducing the rate of growth, i.e. make sure we only make the minimal number of calls with the minimal number of parameters in those scenarios, so that we can process a much larger model without hitting a stack overflow. 

2. Remove the recursion altogether by pulling type discovery as a separate phase before conventions are applied. This would probably have some side effects in the resulting model that we need understand better.

**Comment by AndriySvyryd** [comment]
Clearing milestone for 1.0.0 triage
