### ISSUE TITLE
Microsoft.EntityFrameworkCore.Tools crashes when a new version of NuGet.packaging is referenced

### ISSUE THREAD

**Issue by skofman1** [aspnet/EntityFramework#5411]
Repro:
1. Create a project that references Microsoft.EntityFrameworkCore.Tools version 1.0.0-preview1-final
2. Add reference to NuGet.Packaging version 3.5.0-rc-1309 (available on https://www.myget.org/F/nugetbuild/api/v3/index.json)

project.json example:

```
"dependencies": {
       "NuGet.Packaging":"3.5.0-rc-1309",
        "Microsoft.EntityFrameworkCore.Tools": {
            "type": "build",
            "version": "1.0.0-preview1-*"
        }
    },

    "frameworks": {
        "net451": { }
    },
    "tools": {
        "Microsoft.EntityFrameworkCore.Tools": {
            "imports": [ "portable-net451+win8" ],
            "version": "1.0.0-preview1-*"
        },
     }

```
Run:
` dotnet ef database update `

The error: 

```
System.MissingMethodException: Method not found: 'Void NuGet.Packaging.VersionFolderPathResolver..ctor(System.String, Boolean)'.
   at Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider..ctor(String packagesPath, FrameworkReferenceResolver frameworkReferenceResolver)
   at Microsoft.DotNet.ProjectModel.ProjectContextBuilder.Build()
   at Microsoft.EntityFrameworkCore.Tools.Cli.OperationExecutor..ctor(CommonOptions options, String environment)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
Method not found: 'Void NuGet.Packaging.VersionFolderPathResolver..ctor(System.String, Boolean)'.
```

The error is caused because Microsoft.EntityFrameworkCore.Tools has a dependency on NuGet.Packaging (through Microsoft.DotNet.Cli.Utils) version 3.5.0-beta-final that is older then version 3.5.0-rc-1309 that is referenced by the project. 

The expected behavior is that project references won't affect a tool.

**Comment by natemcmaster** [comment]
This is a general problem for all dependency-type tools because these tools are not isolated from the app's dependencies. 

"Microsoft.DotNet.Cli.Utils" has an open-ended dependency.

```xml
<dependency id="NuGet.Packaging" version="[3.5.0-beta-final, )" />
```

This means there are no guardrails and, you--the app developer--must ensure peer dependencies added to your app are compatible with the tool. 

Solution: specify compatible [version ranges](https://docs.nuget.org/create/versioning#specifying-version-ranges-in-.nuspec-files) in "Microsoft.DotNet.Cli.Utils". NuGet restore would then surface this incompatibility in restore.

This same issue will apply to any other dependency-type tool that depends on Microsoft.DotNet.Cli.Utils, including dotnet-razor-tooling, dotnet-aspnet-codegenerator, dotnet-test-xunit and others.

cc @davidfowl @NTaylorMullen @piotrpMSFT @prafullbhosale
