### ISSUE TITLE
HasKey and ValueGeneratedOnAdd have a declaration order dependency

### ISSUE THREAD

**Issue by alexandru-calinoiu** [aspnet/EntityFramework#5776]
### Steps to reproduce

__PropertyClassEntity__
```c#
    public class PropertyClassEntity
    {
        public override PropertyClassEntityTypeEnum Id { get; set; }
    }
```

__PropertyEntity.cs__
```c#
    public sealed class PropertyEntity : Entity
    {
        public PropertyClassEntity PropertyClass { get; set; }
    }
```

__PropertyClassEntityTypeEnum__
```c#
    public enum PropertyClassEntityTypeEnum : byte
    {
        A = 1,
        B,
        C
    }
```
__CommonMapping__ (works)
```c#
            builder.Property(t => t.Id).ValueGeneratedOnAdd();
            builder.HasKey(t => t.Id);
```

__CommonMapping__ (does not work)
```c#
            builder.HasKey(t => t.Id);
            builder.Property(t => t.Id).ValueGeneratedOnAdd();
```

### The issue
When trying to save the PropertyEntity it will throw the following error:

```
Result Message:	The property 'Id' on entity type 'PropertyClassEntity' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.
```

### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: Win10
Visual Studio version: VS 2015

**Comment by ajcvickers** [comment]
Notes for triage: I wasn't able to reproduce the exact exception, probably because there is a lot of missing information in the repro code, but I did find the likely root cause. When ValueGeneratedOnAdd is set a check is made for whether the property is part of a key. If it is, then it gets the RequiresValueGenerator flag set so that the stack will know to generate temporary key values. For non-key properties this does not happen. But if something is made a key, then there is no code that goes back and checks whether any properties have OnAdd set, so in this case the temporary keys are not created.

I think there may be other issues around byte and/or enum keys, so I am going to do further investigation.
