### ISSUE TITLE
Query: TPH query with shared column includes column multiple times.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#5909]
See InheritanceSqlServerTest.Can._query_all_types_when_shared_column

Note: query returns correct results.

Model:
```C#
    public class Drink
    {
        public int Id { get; set; }
    }

    public class Coke : Drink
    {
        public int SugarGrams { get; set; }
    }

    public class Lilt : Drink
    {
        public int SugarGrams { get; set; }
    }
```
Query:
```C#
var drinks = context.Set<Drink>().ToList();
```
SQL:
```SQL
SELECT [d].[Id], [d].[Discriminator], [d].[SugarGrams], [d].[SugarGrams] 
FROM [Drink] AS [d]
WHERE [d].[Discriminator] IN (N'Lilt', N'Coke', N'Drink')
```

**Comment by smitpatel** [comment]
It is repeated multiple times because metadata has 2 different properties. So while adding to projection it does not seem as duplicate. Migration is the part which merges 2 different properties in on column because all facets being matching. Query does not match such column at present and `SelectExpression` has no access to relational annotation to identify property with same column name.
@anpete @maumar - Thoughts on how to do this?

**Comment by anpete** [comment]
@smitpatel Why can't we access the annotation? We have the IProperty.

**Comment by smitpatel** [comment]
@anpete - Read annotation directly from metadata?

**Comment by anpete** [comment]
@smitpatel Lets chat.
