### ISSUE TITLE
Guidance on PORTING from EF6 to EF7

### ISSUE THREAD

**Issue by rustd** [aspnet/EntityFramework#615]
We should think about what is our compatibility story for apps/database written/created using EF 6. 
What happens when the app is upgraded to use EF 7, but the user wants to use the same database/ tables that were created with EF 6 and the user was potentially using migrations as well.

**Comment by npnelson** [comment]
I just ran into the need to access tables from an existing EF6 context in a new EF7 project.  I came across this thread while researching what (if any) guidance existed.  The only answer I could come up with is to create the new tables in the EF6 based DbContext, run the migrations from EF6 and then create another context for EF7, but not run any migrations from EF7  

The only thing that bit me (so far) was #604, so I had to explicitly configure each table name in the EF7 model to make it plural.

At a minimum, I think you will have to do something with the migrationhistory table.  At least users would be able to upgrade their applications per context instead of per database for those who have multiple contexts hitting their database (which is increasingly common since Azure charges by the database).

I think you will also need to provide some guidance by RTM for developers who want to use EF7 for new work on existing EF6 contexts but might not have time to go back and upgrade all of their EF6 apps.  Even if the guidance turns out to be less than ideal (i.e. maintain an EF6 and EF7 context but only run migrations from EF6 until you can upgrade all your apps to EF7)

On a side note, I am really excited about the new ASPNET stack and having the code and issues out in the open has been a huge help.  I think all the work that is being put into this new stack is fantastic and I am learning a lot from you.
