### ISSUE TITLE
Make more services singletons

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#6924]
There are currently some services that could be registered as singletons, reducing the number of allocations we have to make for each `DbContext` instance:
1. Services that no longer need to be scoped, such as `IInternalEntityEntryFactory` 
1. Services that have no mutable state, but use scoped services like `ICurrentDbContext` or `IDbContextOptions` in one of the methods and can be refactored to pass the required services in the method call itself, such as `IChangeTrackerFactory` (we should measure the performance/memory benefit of this in a case by case basis and understand if the breaking change and possibly more coupled or complex code is worth it)
1. Services that have a cache and could be refactored to use `DbContextServices.MemoryCache`, such as  `IValueGeneratorSelector` (already tracked by #5322)
1. Services that depend on one or more of the above, such as `IKeyPropagator`

Doing this would allow us to cache these services and not use DI to get them. On the other hand the DI resolution can be significantly sped up by not using delegates with `GetService` calls in them for registration, see #4133.

**Comment by ajcvickers** [comment]
Some additional thoughts on this:

* Consider changing IDatabaseProviderServices so that it can be implemented as a singleton. This would mean that each provider would have a singleton instance, with the one being returned in the scope being the one fore the selected provider. It could then cache singleton provider services to avoid a GetService call. The service provider could no longer be injected and instead should be passed to each method that needs to resolve a scoped service.
* Consider not allowing a different logger per context instance. The dependency on ILogger, which is scoped because a different logger can be used for each context instance, is a big factor in forcing services to be scoped.
* Consider not allowing the model to change for each context instance, or passing the model to services that need it rather than depending on it through injection.
