### ISSUE TITLE
Use a relational provider for Relational.Tests and Design.FunctionalTests

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#7202]
Currently these tests run against InMemory which doesn't have the relational conventions/services resulting in the wrong code being tested.

**Comment by divega** [comment]
**Triage decision:** All tests in this package should be run against specific providers. We don't need to run them against InMemory and we don't need to create a relational provider that works to run these test. There are areas in Relational that we want to make sure we cover in unit tests, e.g. because most providers may override the default implementation, so specification teste would not provide coverage for the default implementation.

**Comment by AndriySvyryd** [comment]
@ajcvickers @divega Oops, there are no relational functional tests that run against InMemory, the issue was actually about the unit tests in Microsoft.EntityFrameworkCore.Relational.Tests

**Comment by divega** [comment]
@AndriySvyryd ok, and what do we use for those? some kind of test double based on Relational?

**Comment by AndriySvyryd** [comment]
We can create a fake provider for the unit tests so they are executed with the correct set of services and we can make all the test classes abstract in Microsoft.EntityFrameworkCore.Design.FunctionalTests

**Comment by divega** [comment]
> we can make all the test classes abstract in Microsoft.EntityFrameworkCore.Design.FunctionalTests

Why abstract in this case? Are the concrete ones supposed  to be provider specific?

**Comment by AndriySvyryd** [comment]
@divega For the same reason we discussed in the triage, functional tests only make sense for a specific provider, even if they are testing shared logic.

**Comment by divega** [comment]
@AndriySvyryd ok, I suspected that... But then if the tests in Microsoft.EntityFrameworkCore.Design.FunctionalTests are going to become abstract should they become part of a specification package?

**Comment by AndriySvyryd** [comment]
We could ship them as Microsoft.EntityFrameworkCore.Design.Specification.Tests, but currently there is very little value in doing so.
