### ISSUE TITLE
Reference Include in derived type with siblings throws invalid cast expression

### ISSUE THREAD

**Issue by Qszer94** [aspnet/EntityFramework#7312]
I have a problem with simple query:
```C#
            var leaves = _context.Proposal.OfType<ProposalLeave>()
                .Include(l => l.Creator).ThenInclude(e => e.User)
                .Include(l=>l.LeaveType)
                .Include(l => l.ProposalLeaveStatuses).ThenInclude(l => l.ProposalLeaveStatus)
                .AsQueryable();
```
 Because of `.Include(l=>l.LeaveType)` I'm getting exception:

```
InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.Int32'
```

### Steps to reproduce
Yesterday I reported the problem on Stack Overflow .
[Here](http://stackoverflow.com/questions/41320728/include-causes-invalidcastexception) you can find whole details of the problem with helpful answer of Ivan Stoev.
I made also VS 2015 project that reproduce this issue.
The project is available for download [here](https://1drv.ms/u/s!AtgBak8wmGjhhAxEmMKDwO1laALG).

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2015

**Comment by divega** [comment]
This looks like it could be caused by an error when we calculate the offsets for each entity in the value buffer. 

@Qszer94 As a workaround you can try loading all LeaveType instances from the database before or after you execute the query without `Include(l=>l.LeaveType)`. If both queries are tracked the relationships between the entities should be fixed up automatically.

@Qszer94 also, was the same query working for you with EF Core 1.0?

**Comment by Qszer94** [comment]
@divega 
**Ad 1**. 
I tried to load all LeaveTypes before my query as you suggested like that:
```var leaveTypes = _context.ProposalLeaveType.ToList();```
but it didn't help until I included ProposalLeaves colletion to all types:
```var leaveTypes = _context.ProposalLeaveType.Include(plt => plt.ProposalLeaves).ToList();```

If we want to fetch just one ProposalLeave we can also:
```
var leave = _context.Proposal.OfType<ProposalLeave>().First(p=>p.ProposalId ==1);
leave.LeaveType = _context.ProposalLeaveType.Find(leave.ProposalLeaveTypeId);
```
**Ad 2.** 
I didn't have any problems with that query and EF Core 1.0. However, at the same time as I update EF dependencies to version 1.1 I made some changes in my models. They were just cosmetic changes like property renaming, so they shouldn't affect the problem.

**Comment by divega** [comment]
Moving to 1.1.1 milestone on the suspicion that this could be a regression. We will need to investigate.

@Qszer94 In case I wasn't clear before, I would have expected the `ProposalLeave.LeaveType` navigation properties to be populated after executing this:

``` C#
var leaveTypes = _context.ProposalLeaveType.ToList();
var leaves = _context.Proposal.OfType<ProposalLeave>()
    .Include(l => l.Creator).ThenInclude(e => e.User)
    .Include(l => l.ProposalLeaveStatuses).ThenInclude(l => l.ProposalLeaveStatus)
    .ToList();
```

That is because `PropsalLeave` contains a foreign key into `ProposalLeaveType`. If that doesn't happen we will also need to investigate it.

**Comment by Qszer94** [comment]
Oh now I see. I didn't remove `.Include(l=>l.LeaveType)` earlier. 
I tested your query. Of course, you were right - it works as expected.

**Comment by anpete** [comment]
@divega Not a regression. Looks to be a dependent issue of #7451 where the unnecessary columns in the projection throw off the value buffer indexes.
