### ISSUE TITLE
InvalidCastException on Where with Any

### ISSUE THREAD

**Issue by NoFear23m** [aspnet/EntityFramework#7657]
Hy all

In my model i have the Entity Businesspartner. The Businesspartner have a Property "Addresses"
Address have a Property ZipCity from type CityZip
CityZip have a Property PostCode

I will make a search, but if i search with the postcode or the City i get the following error:
`System.InvalidCastException: Das Objekt des Typs "<SelectManyIterator>d__16`2[Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryTableSnapshot,Microsoft.EntityFrameworkCore.Storage.ValueBuffer]" kann nicht in Typ "System.Collections.Generic.IEnumerable`1[SPS.DMS.Model.Common.Address]" umgewandelt werden.`

I have attached an Image from my model. 
![screenshotmodel](https://cloud.githubusercontent.com/assets/15660141/23093603/45c7680a-f5e8-11e6-804e-37911c1e2c70.PNG)

Here ist my Querycode:

`  Dim bpQuery As IQueryable(Of BusinessPartner) = From bp As BusinessPartner In Ctx.BusinessPartners.Include(Function(i) i.Addresses).ThenInclude(Function(i1) i1.ZipCity)
                                                        Select bp

        bpQuery = bpQuery.AsNoTracking

        'Gelöschte aus suche ausschliessen?
        If Not includeDeleted Then bpQuery.Where(Function(b) b.DeletedFlag = False)

        'Wenn BP Nummer dann ist ergebniss klar
        If bpNumber > 0 Then
            bpQuery = bpQuery.Where(Function(b) b.BusinessPartnerId = bpNumber)
            Return bpQuery.ToList
        End If

                Dim nameStringList As List(Of String) = namestring.ToLower.Split(" ").ToList

            For i As Integer = nameStringList.Count - 1 To 0 Step -1
                If nameStringList(i) = " " OrElse nameStringList(i) = "" Then nameStringList.RemoveAt(i)
            Next

            bpQuery = bpQuery.Where(Function(b) (b.FirstName IsNot Nothing AndAlso nameStringList.Any(Function(l) b.FirstName.ToLower.Contains(l))) OrElse
              (b.MiddleName IsNot Nothing AndAlso nameStringList.Any(Function(l) b.MiddleName.ToLower.Contains(l))) OrElse
               (b.LastName IsNot Nothing AndAlso nameStringList.Any(Function(l) b.LastName.ToLower.Contains(l))))

        End If

        If Not String.IsNullOrEmpty(firstname) Then bpQuery = bpQuery.Where(Function(b) b.FirstName.ToLower.Contains(firstname.ToLower))
        If Not String.IsNullOrEmpty(lastname) Then bpQuery = bpQuery.Where(Function(b) b.LastName.ToLower.Contains(lastname.ToLower))
        If Not String.IsNullOrEmpty(taxnumber) Then bpQuery = bpQuery.Where(Function(b) b.TaxNumber.ToLower.Contains(taxnumber.ToLower))
        If Not String.IsNullOrEmpty(matchcode) Then bpQuery = bpQuery.Where(Function(b) b.Matchcode.ToLower.Contains(matchcode.ToLower))

        **If postcode IsNot Nothing Then
            bpQuery = bpQuery.Where(Function(plz) plz.Addresses.Any(Function(a) a.ZipCity.ZipCode = postcode))
        End If
        If city IsNot Nothing Then
            bpQuery = bpQuery.Where(Function(x) x.Addresses.Any(Function(y) y.ZipCity.City.ToLower.Contains(city.ToLower)))
        End If**

        If excludeCompanys Then
            bpQuery = bpQuery.Where(Function(b) b.IsCompany = False)
        End If
        If excludePersons Then
            bpQuery = bpQuery.Where(Function(b) b.IsCompany = True)
        End If

        Dim resultList As List(Of BusinessPartner) = bpQuery.ToList

        Return resultList`

What is my mistake??

Thanks in advance for your time.
Best Regards
Sascha

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
Can you also let us know what version of EF Core you are using

**Comment by NoFear23m** [comment]
OK, sorry.
My Version is 1.1.0

OK, i will make a testsolution and load it up in the next days. At the moment the code is in a big projekt with totaly 43 projects in my solutionexplorer.

btw: today i have changed this
`  If city IsNot Nothing Then
        bpQuery = bpQuery.Where(Function(x) x.Addresses.Any(Function(y) y.ZipCity.City.ToLower.Contains(city.ToLower)))
    End If`

to this
`If city IsNot Nothing Then
            bpQuery = From b As BusinessPartner In bpQuery Join a As Address In Ctx.Addresses On b.BusinessPartnerId Equals a.BusinessPartnerId
                      Where a.ZipCity.City.Contains(city) Select b
        End If`

Now it will work. Maybe this also help you.

Sorry for my mistake :-(
Greets
Sascha

**Comment by maumar** [comment]
Verified that this works in current bits, closing
