### ISSUE TITLE
Discuss improvements for our usage of AppVeyor and Travis

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#7837]
See discussion at https://github.com/aspnet/EntityFramework/pull/7825. 

In summary, these checks could be useful mostly for external PRs but they are not as useful because they are too noisy (e.g. tests often fail arbitrarily, especially in AppVeyor). @natemcmaster has checked in a change that makes AppVeyor opt-in which may help in reducing the noise, but there are other possible approaches we would like to discuss.

**Comment by natemcmaster** [comment]
I liked the suggestion @smitpatel made - is it possible to trigger builds on PRs from comments? The dotnet team has setup @dotnet-bot to trigger builds on netci.

**Comment by Eilon** [comment]
Yeah not sure what AppVeyor can do... but I'd really like it to run by default for all PRs to make sure someone didn't make a bone-headed mistake, and also especially for community PRs (where the process might not be clear or obvious). I think running a much smaller set of tests would go a long way towards that, especially if reliability and time are the big concerns.

**Comment by ajcvickers** [comment]
Discussed this in triage and came to the following conclusions:
* Appveyor doesn't have much value for PRs from the team because we have a culture of testing before pushing
* There could be more value for external PRs where people may not have built or tested before submitting the PR
* But...AppVeyor would have to be much more reliably passing for this to be actually useful.
* Travis has more value even within the team because we don't typically develop/test on non-Windows machines
* Travis would also help with the external PR verification
* Nate is looking into running SQL Server tests on travis--experimental PR #7842 

Based on all of this, we came to the conclusion that if travis was reliable and ran SQL Server tests, than this would provide the most value going forward. @Eilon Any push back on going in this direction?

**Comment by Eilon** [comment]
This sounds good. Let's keep Travis green 😄

**Comment by natemcmaster** [comment]
So, we almost got SQL Server + Travis working. Travis killed the build at 50 minutes.

I would guess it will run even longer than AppVeyor took. The perf of SQL Server in Docker is not great. SQL Server on the host instead of docker isn't going to work yet because Travis agents aren't on Ubuntu xenial yet: https://github.com/travis-ci/travis-ci/issues/5821

**Comment by divega** [comment]
Sound like we would need to run only a subset of SQL Server tests then, regardless of whether we use Travis or AppVeyor.

**Comment by smitpatel** [comment]
The idea of running non-sql server tests on travis and only sql server tests on appveyor can be good too. If AppVeyor can handle that load.

**Comment by natemcmaster** [comment]
Still playing around this. I've started a build with tests broken up into groups:

https://ci.appveyor.com/project/aspnetci/entityframework/build/1.0.4250
![image](https://cloud.githubusercontent.com/assets/2696087/23817927/d3e7b586-05ab-11e7-8cc6-f4c58f801675.png)

https://travis-ci.org/aspnet/EntityFramework/builds/209945475
![image](https://cloud.githubusercontent.com/assets/2696087/23817935/ddda0aee-05ab-11e7-9cbd-57d23787e8d5.png)

**Comment by ajcvickers** [comment]
I think maybe it is time to create this fast subset of tests. We have talked about it on and off for years, and it has come up in several contexts over the past few days. Let's discuss on Monday.

**Comment by natemcmaster** [comment]
Something appears to be wrong with the SQL Server functional tests. Here are the results:

- Travis - https://travis-ci.org/aspnet/EntityFramework/builds/209958734
  - ✅ Unit tests (*.Tests.csproj) 8.5 min 
  - ✅ Functional tests w/o SQL Server (*.FunctionalTests.csproj) 12.5 min
  - :x: SqlServer.Design.FunctionalTests + SqlServer.FunctionalTests - timed out after 50 minutes
- AppVeyor - https://ci.appveyor.com/project/aspnetci/entityframework/build/1.0.4258
  - ✅ Unit tests 20 min
  - :x: Functional tests (including SQL Server) - timed out after 60 minutes

**Comment by Eilon** [comment]
BTW from @dougbu 's email (that a few of you are on), it seems we do have a few very long running tests (60sec+), and no doubt a lot that take 30-60sec, on our relatively fast internal CI. I can only imagine how much slower they are on other hardware. That might be a good place to start a plan of attack.

**Comment by natemcmaster** [comment]
On our internal CI, EntityFramework takes about an hour to pass. The build history shows a sudden jump from 40 minutes to 60 minutes that corresponds to VS 2017 conversion.

![image](https://cloud.githubusercontent.com/assets/2696087/23867423/0c70594c-07d9-11e7-9056-05232973a29a.png)

This is likely another casualty of https://github.com/Microsoft/vstest/issues/349. In addition to making other test perf improvements, we should look into using faster test runners -- like xunit.console -- instead of xunit.runner.visualstudio.

**Comment by ajcvickers** [comment]
Discussed in triage and this is the plan:
* Come up with a subset of tests that should run faster and cover all but corner cases. We will uses this subset for aspnetci runs and Travis. We will continue to run the full set on efci and on developer boxes.
* Investigate some suspicious slow-running tests from those identify by Doug and see if they can be sped up.
* Re-prioritize getting the parallel runs to work again, at least on the fast subset of tests

**Comment by ajcvickers** [comment]
Self-assigning for now to come up with the test subset.

**Comment by smitpatel** [comment]
Created #7880 which was very log-hanging fruit.

**Comment by ajcvickers** [comment]
Closing this for now because it looks like we are currently in a pretty good place with AppVeyor/Travis.

**Comment by smitpatel** [comment]
@divega - Should this be considered Enhancement? Purely our testing thing.
