### ISSUE TITLE
Analyse functional impact of loop error

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#7927]
PR #7909 fixes a bug where the wrong variable is being used in a for loop. We should analyse what functional impact this change makes and then make a call as to whether to port this to 1.1.2

**Comment by smitpatel** [comment]
I added test to observe the behavior of query cache in the presence of the error. While `GetHashCode` gave same result for different expressions due to error, `Equals` method still identified them differently, hence adding 2 different cache entries. The only impact error had was bit more time spent in comparison because `GetHashCode` did not return correct results and caused `Equals` comparison.
