### ISSUE TITLE
Possible include where bug

### ISSUE THREAD

**Issue by PawOrmstrupMadsen** [aspnet/EntityFramework#7979]
This works as intended

![image](https://cloud.githubusercontent.com/assets/11302862/24297311/9ca8a18c-10a2-11e7-9deb-9fbec6f505c5.png)

This creates an sql call for every image in the list (not intended)
![image](https://cloud.githubusercontent.com/assets/11302862/24297345/b9760d22-10a2-11e7-8e3e-69ea64fac01e.png)

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by divega** [comment]
The repro code for this issue was provided in https://github.com/aspnet/EntityFramework/issues/7978#issuecomment-289569617: [files.zip](https://github.com/aspnet/EntityFramework/files/873580/files.zip).

**Comment by maumar** [comment]
Verified this is fixed in current bits, we produce the following:

```sql
SELECT [x].[ProductId], [x].[CollectionOnline], [x].[Compositions], [x].[Details], [x].[ImageBankOnline], [x].[ModelNumber], [x].[Name]
                FROM [Products] AS [x]
                WHERE ((([x].[CollectionOnline] = 1) AND EXISTS (
                    SELECT 1
                    FROM [ProductTypeProducts] AS [w]
                    WHERE ([w].[ProductType_ProductTypeId] = @__productTypeId_0) AND ([x].[ProductId] = [w].[Product_ProductId]))) AND EXISTS (
                    SELECT 1
                    FROM [ImageProducts] AS [y]
                    INNER JOIN [Images] AS [y.Image] ON [y].[Image_ImageId] = [y.Image].[ImageId]
                    WHERE ([y.Image].[ImageCategory] = 0) AND ([x].[ProductId] = [y].[Product_ProductId]))) AND EXISTS (
                    SELECT 1
                    FROM [ImageProducts] AS [y0]
                    INNER JOIN [Images] AS [y.Image0] ON [y0].[Image_ImageId] = [y.Image0].[ImageId]
                    LEFT JOIN [ImageTypes] AS [y.Image.ImageType] ON [y.Image0].[ImageType_ImageTypeId] = [y.Image.ImageType].[ImageTypeId]
                    WHERE ([y.Image.ImageType].[ImageTypeId] = 1) AND ([x].[ProductId] = [y0].[Product_ProductId]))
                ORDER BY [x].[ProductId]
```

and one additional query to include ImageProducts collection:

```sql
SELECT [x.ImageProducts].[Image_ImageId], [x.ImageProducts].[Product_ProductId], [i.Image].[ImageId], [i.Image].[CollectionPriority], [i.Image].[Filename], [i.Image].[ImageCategory], [i.Image].[ImageType_ImageTypeId], [i.Image].[InCollection], [i.Image.ImageType].[ImageTypeId], [i.Image.ImageType].[Name]
                            FROM [ImageProducts] AS [x.ImageProducts]
                            INNER JOIN [Images] AS [i.Image] ON [x.ImageProducts].[Image_ImageId] = [i.Image].[ImageId]
                            LEFT JOIN [ImageTypes] AS [i.Image.ImageType] ON [i.Image].[ImageType_ImageTypeId] = [i.Image.ImageType].[ImageTypeId]
                            INNER JOIN (
                                SELECT [x0].[ProductId]
                                FROM [Products] AS [x0]
                                WHERE ((([x0].[CollectionOnline] = 1) AND EXISTS (
                                    SELECT 1
                                    FROM [ProductTypeProducts] AS [w0]
                                    WHERE ([w0].[ProductType_ProductTypeId] = @__productTypeId_0) AND ([x0].[ProductId] = [w0].[Product_ProductId]))) AND EXISTS (
                                    SELECT 1
                                    FROM [ImageProducts] AS [y1]
                                    INNER JOIN [Images] AS [y.Image1] ON [y1].[Image_ImageId] = [y.Image1].[ImageId]
                                    WHERE ([y.Image1].[ImageCategory] = 0) AND ([x0].[ProductId] = [y1].[Product_ProductId]))) AND EXISTS (
                                    SELECT 1
                                    FROM [ImageProducts] AS [y2]
                                    INNER JOIN [Images] AS [y.Image2] ON [y2].[Image_ImageId] = [y.Image2].[ImageId]
                                    LEFT JOIN [ImageTypes] AS [y.Image.ImageType0] ON [y.Image2].[ImageType_ImageTypeId] = [y.Image.ImageType0].[ImageTypeId]
                                    WHERE ([y.Image.ImageType0].[ImageTypeId] = 1) AND ([x0].[ProductId] = [y2].[Product_ProductId]))
                            ) AS [t] ON [x.ImageProducts].[Product_ProductId] = [t].[ProductId]
                            ORDER BY [t].[ProductId]
```
