### ISSUE TITLE
Flaky Test: Dozens of "IOException : Pipe is broken" test failures

### ISSUE THREAD

**Issue by halter73** [aspnet/EntityFramework#8416]
```
System.IO.IOException : Pipe is broken.
```

http://aspnetci/viewLog.html?buildId=217358&tab=buildResultsDiv&buildTypeId=Lite_EntityFrameworkTest

@divega Do you know who should look into this?

**Comment by divega** [comment]
cc @ajcvickers @smitpatel

**Comment by smitpatel** [comment]
The error is coming from SqlClient. It started occurring when we upgraded packages to 4.4.0-*. We had to do upgrade because 4.3.0 started hanging on windows 7 & Server 2008 https://github.com/dotnet/corefx/issues/18406

The upgrade brought in few other issues. One of them was above issue. Which was successfully fixed in https://github.com/dotnet/corefx/issues/19057

While everything in source code is already been fixed & updated package is provided by core fx already, this is our infrastructure issue. Mirror package did not run correctly for dev (and it is failing for 10 days now), hence we have new package on feed (so projects->EF passes correctly) but not in package share which is used while running tests during universe build. Since Mirror ran correctly on preview1, that branch is still green. Last I inquired about the issue, I was told that we are not putting time in fixing dev till we get preview1 finalized.

@mikeharder is current investigator of the issue and aware of the situation.
@kichalla who provided insights on the error produced by Mirror packages.

This issue has been discussed in mails & in ASPNET-CI channel in teams already. I checked out that it is also noted down in OneNote in sufficient detail.
We need to have a streamlined system at tracking build/infra issue so that anyone can just check one place and be aware of the situation. @eilon

**Comment by halter73** [comment]
@smitpatel Can you point me to where this issue is mentioned in OneNote so I know where to check next time?

**Comment by smitpatel** [comment]
DotNetServer Notebook -> Build failures-> Open Issues.

Though I am not certain on how latest the docs are kept.

**Comment by kichalla** [comment]
@smitpatel just fyi...we had a successful mirror build in dev few minutes back

**Comment by Eilon** [comment]
@smitpatel - it should be up-to-date, but of course sometimes we might miss things. But I have started a plan to make sure things stay even more up-to-date, so stay tuned! 😄

**Comment by smitpatel** [comment]
This is fixed in CI now.
