### ISSUE TITLE
Recent changes to MonsterModel breaks SQL CE provider test

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#8496]
https://github.com/aspnet/EntityFramework/commit/e6f0e1921216e46de774d8b55785223617982d3d
introduced use of IAuditInfo and other new Interface that contain DateTime properties. Since no value is supplied, these values default to DateTime.MinValue, which breaks INSERTs with SQL CE, as it only supports SqlDateTime.MinValue - I have helped fix this earlier, but unsure of the best way to fix now, since IAuditInfo is an owned entity. @AndriySvyryd

**Comment by smitpatel** [comment]
@ErikEJ - The `AuditInfo` DIET is newly added in tests which is causing the issue. The simplest way to do this to set the value of the date in the ctor of `AuditInfo` entity since we are not assigning any values to it during seed methods (`SeedUsingFks`, `SeedUsingNavigations` etc). Can you submit a PR for this? I think DateTime.Now would also work as value.

Ref line:
https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Specification.Tests/TestModels/SnapshotMonsterContext.cs#L445

And other 2 variations of MonsterContext in same folder.
