### ISSUE TITLE
Default escape behavior for LIKE

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#8696]
Now that 2.0.0 will have support for LIKE, it's time to obsess over the minor details.

By default, PostgreSQL considers backslash an escape character in LIKE expressions, whereas SqlServer seems to have no escape character by default. I'm not sure what the C# implementation you wrote does, but I'm wondering if we want to define a single behavior to be followed by providers (as best as possible). If the no-escape-by-default is to be the default, Npgsql can generate a no-escape clause - but the documentation should also probably be updated.

Another related note, is that it currently seems impossible for a provider to override an expression translator that has been added in Relational (e.g. LikeTranslator) - RelationalCompositeMethodCallTranslator doesn't allow accessing the translator list other than via `AddTranslator`. Would you guys accept a PR making the method translator list protected, and moving the translators themselves out of Internal?

**Comment by divega** [comment]
@roji Good point about the default behavior with no escape character. I like the idea of documenting that providers should if possible disable escaping for that case. That aligns with standard SQL. We will discuss it in triage and come back to you. 

> ... it currently seems impossible for a provider to override an expression translator that has been added in Relational (e.g. LikeTranslator)

@maumar I remember we did something to allow overriding the translators already, e.g. for `String.StartsWith()`. What is the intended pattern?

cc @anpete

**Comment by smitpatel** [comment]
For point 2, I believe `AddTranslator` is sufficient and way to override any translator. The way it is designed is, provider specific translators are added in the list first (at 0 index). So if provider adds a translator which can translate Like Expression (regardless of it overriding from relational one), then translation short circuits and the relational one will never get called. Let us know if you need more help in adding postgre specific Like translator. It should just work by design.
The only thing impossible for providers at present is to remove a relational translator. If there is any such case, then we need to determine if that translator belongs to relational or should moved providers.

**Comment by divega** [comment]
Ah, yes, that @smitpatel says is the pattern....

**Comment by ajcvickers** [comment]
@anpete to follow up with @roji

**Comment by roji** [comment]
Sounds good with regards to `AddTranslators()`, thanks! Will wait for the default behavior discussion.

**Comment by anpete** [comment]
@roji We decided to go with no-escape-by-default. I am going to add a test that verifies this behavior for some common escape chars.

**Comment by roji** [comment]
@anpete ok, I'll make the adjustments in the Npgsql provider to implement this, will wait for your test.
