### ISSUE TITLE
Investigate if name/schema are the correct identifiers for store functions

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8941]

**Comment by divega** [comment]
There is some variability on what is supported among the most popular relational databases but there is nothing special about functions that doesn't apply to tables. I think it is reasonable to have Relational assume that schema, function name and arguments are sufficient to identify a function. 

Some database support packages (e.g. Oracle) which are installed in a schema, leading to objects from the package (e.g. tables and functions) to have three-part names. I think the Oracle provider will have to add its own extensions to annotate objects with package name in order to support referencing objects defined in packages. 

Some and others support overloads with the same name in the same schema (e.g. DB2). 

Details:
- SQLCE: no schemas, no packages support.
- SQLite: main and temp schemas available by default, it is possible to attach other database files assigning separate schemas (but according to @bricelam we don't support that yet).
- Oracle: functions can be defined both in schemas and in logical groupings named packages. The fully qualified name of a function can be of the form `SchemaName.PackageName.FunctionName`.
- MySQL: there are no schemas, or in a different interpretation, schemas and databases are synonyms and cross-database queries are supported. There are no packages.
- PostgreSQL: Extensions are the equivalent of a package. But objects created by an extensions belong in the schema in which the extension was installed. They are not considered to have their own grouping and multi-part identifiers should not be needed for this.
- DB2: from what I was able to understand, packages can install objects in schemas, similar to PostgreSQL extensions.

**Comment by ajcvickers** [comment]
Thanks for doing the investigation!
