### ISSUE TITLE
Stack Overflow during model creation

### ISSUE THREAD

**Issue by Wain123** [aspnet/EntityFramework#9099]
I have a large-ish model, consisting of 452 entities and 1153 relationships. Today I added one more unmapped get-only property to each entity, and subsequently received a stack overflow exception during model creation, in one of the lines that look like
`builder.HasOne(t => t.User).WithMany("AdrUserMandantUserCollection").HasForeignKey("User_Seqnr").OnDelete(DeleteBehavior.Restrict);`
Changing the order of Fluent API calls changes the exact line that throws the exception, and removing most (but not necessarily all) of the new properties causes the exception to not occur. Alternatively, replacing the properties with functions also causes the exception to not occur.

So, the only conclusion I can draw is that the stack usage during model creation is proportional to the number of properties on my mapped entity classes. Is this working as intended, and is there a way to reduce the stack usage? My model can only grow in the future, and increasing the stack size is somewhat inconvenient in this particular application.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

### Further technical details
### EF Core version: (found in project.json or packages.config)
### Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
### Operating system: 
### IDE: (e.g. Visual Studio 2015)

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by Wain123** [comment]
Apologies, here are more details.

EF Core version: 1.1.2
Database Provider: Devart.Data.Oracle 9.4.299.0
Operating system: Windows 10 Pro version 1607
IDE: Visual Studio 2017

The stack trace in the actual exception is null (I don't understand why), but I can give you Visual Studio's call stack (attached as a file because it's huge):

[stack.txt](https://github.com/aspnet/EntityFramework/files/1134822/stack.txt)

**Comment by ajcvickers** [comment]
@Wain123 There have been big improvements in this area for 2.0--conventions now use a lot less stack space, so I'm going to close this a fixed. Please try it with 2.0 preview2 or the nightly builds as soon as you can and feel free to re-open if the issue still repros.
