### ISSUE TITLE
"Add-Migration" In UWP

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#9141]
_From @hippieZhou on July 9, 2017 7:14_

When I follow this [link](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started) Sample Step by Step, When I Run Add-Migration MyFirstMigration to scaffold a migration to create the initial set of tables for my model.I got something wrong,the error info is that  **" Could not load type 'System.ComponentModel.DataAnnotations.Schema.InversePropertyAttribute' from assembly 'System.ComponentModel.Annotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"**,all of this package is  latest version ,and the UWP SDK version is  15063 .Can you tell me what should I do to fix it. thank you. 

_Copied from original issue: aspnet/EntityFramework.Docs#419_

**Comment by bricelam** [comment]
@hippieZhou What version of `Microsoft.EntityFrameworkCore.Tools` are you using and what version of `Microsoft.NETCore.UniversalWindowsPlatform`?

**Comment by hippieZhou** [comment]
The .csproj info is that:

<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite">
      <Version>1.1.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <Version>1.1.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
     <Version>5.3.3</Version>
    </PackageReference>
  </ItemGroup>

I use VS2017 to dev .

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Brice Lambson<mailto:notifications@github.com>
发送时间: 2017年7月11日 23:38
收件人: aspnet/EntityFramework<mailto:EntityFramework@noreply.github.com>
抄送: hippie<mailto:hippieZhou@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [aspnet/EntityFramework] "Add-Migration" In UWP (#9141)


@hippieZhou<https://github.com/hippiezhou> What version of Microsoft.EntityFrameworkCore.Tools are you using and what version of Microsoft.NETCore.UniversalWindowsPlatform?

―

**Comment by divega** [comment]
@hippieZhou what version of Windows and .NET Framework do you have installed? 

I am investigating a similar repro with the same exception on a machine that has a Windows 10 build 16241 ([recently made available in the Windows Insider Program](https://blogs.windows.com/windowsexperience/2017/07/13/announcing-windows-10-insider-preview-build-16241-pc-build-15230-mobile/)) which happens to contain a newer build of .NET Framework 4.7, and I am observing that the copy of System.ComponentModel.Annotations this machine has in the GAC doesn't in fact contain the type forwarding for InversePropertyAnnotation. 

I suspect it might be a regression in in recent builds of Windows 10 and/or .NET Framework since other machines with older builds of .NET Framework have the type forwarding.

**Comment by hippieZhou** [comment]
My Windows version is 16241,and .NET Framework version is 4.7,Maybe you are right !
Thanks for your help.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Diego Vega<mailto:notifications@github.com>
发送时间: 2017年7月17日 16:14
收件人: aspnet/EntityFramework<mailto:EntityFramework@noreply.github.com>
抄送: hippie<mailto:hippieZhou@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [aspnet/EntityFramework] "Add-Migration" In UWP (#9141)


@hippieZhou<https://github.com/hippiezhou> what version of Windows and .NET Framework do you have installed?

I am investigating a similar repro with the same exception on a machine that has a Windows 10 build 16241 (recently made available in the Windows Insider Program<https://blogs.windows.com/windowsexperience/2017/07/13/announcing-windows-10-insider-preview-build-16241-pc-build-15230-mobile/>) which happens to contain a newer build of .NET Framework 4.7, and I am observing that the copy of System.ComponentModel.Annotations this machine has in the GAC doesn't in fact contain the type forwarding for InversePropertyAnnotation.

I suspect it might be a regression in in recent builds of Windows 10 and/or .NET Framework since other machines with older builds of .NET Framework have the type forwarding.

―

**Comment by nerdile** [comment]
Is there a workaround for running Add-Migration on an affected build?

**Comment by divega** [comment]
This issue has been fixed and the fix should become available in future Windows builds. 

Until the fix is available the best workaround I can think of is to move the entity types and the `DbContext` into a .NET Standard library and then creating a .NET Core console app. 

Both the console app and the original app should reference the library. 

Then you should be able to execute migrations commands pointing to the console app.

**Comment by divega** [comment]
Another less convinient workaround could be to do the work of add-migrations manually, e.g. creating and modifying all the necessary files in the project.

**Comment by divega** [comment]
I have personally validated the scenario with a build of System.ComponentModel.Annotations.dll that contains the fix. I am closing this because the issue is no longer actionable on our side, but unfortunately it may take some time for the fix to flow all the way to Windows Insider builds.
