### ISSUE TITLE
Migrations: Support database schemas

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#948]
Created a relational model and tried to used a custom, non-existent db schema. Database creation failed because it looks like migrations has no support for creating database schemas.

**Comment by bricelam** [comment]
Re-opening. I've regressed this.

**Comment by rowanmiller** [comment]
When you work on this the ModelDiffer currently throws if you add a schema since it tries to create an operation to move from an unspecified (and therefore null) schema.

> System.ArgumentNullException: Value cannot be null.
Parameter name: newSchema
   at Microsoft.Data.Entity.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.Data.Entity.Relational.Migrations.Operations.MoveTableOperation..ctor(String name, String schema, String newSchema, IReadOnlyDictionary`2 annotations)
   at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.ModelDiffer.<Diff>d__15.MoveNext()

**Comment by bricelam** [comment]
Notes from today's design meeting:
* When a new schema is encountered in the model differ, we'll scaffold a CreateSchema operation
* CreateSchema will create the schema if it doesn't already exists
* We'll never scaffold DropSchema, but it can manually be added to the migration

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFramework/blob/dev/test/EFCore.CrossStore.FunctionalTests/TestModels/CrossStoreContext.cs#L23
