### ISSUE TITLE
Allow referencing EF from a strong-named assembly

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#999]
Since the current builds of EF are not strong-named, if you try to reference them from a strong-named assembly, you will get the following warning during build...

> CSC : warning CS8002: Referenced assembly 'EntityFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

...and the following exception at runtime.

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'EntityFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by bricelam** [comment]
The runtime is going to enable us to strong name.

**Comment by bricelam** [comment]
Re-opening to verify

**Comment by bricelam** [comment]
Verified.

**Comment by rowanmiller** [comment]
@bricelam are our builds actually strong named now, or have we just verified it is possible?

**Comment by bricelam** [comment]
Just verified that it's possible. They're (@moozzyk?) going to enable it on all our packages.

**Comment by rowanmiller** [comment]
Cool, just going to reactivate this one to track the scenario on our side (since we are the main package in need of it).

**Comment by rowanmiller** [comment]
@moozzyk any update on this one? I know we added the ability to strong name, but the assemblies EF depends on (DI, Config, Logging, etc.) are still not being strong named.

**Comment by moozzyk** [comment]
@rowanmiller - talked to @muratg about this. Created an issue in the dnx repo to track this.

**Comment by rowanmiller** [comment]
Spoke with @moozzyk and we are aiming to enable this in Beta8

**Comment by hkoestin** [comment]
Is there any progress concerning this topic?
When can I expect Beta8 to be released? 
Or which nightly build is already supporting signed assemblies?

Whereas I was able to just "brute-force" sign my EF7-beta7 assemblies with some tools, I neither can execute the application nor the unit tests now.

Getting the following error: 

**System.MethodAccessException - [\Debug\Microsoft.Framework.DependencyInjection.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.**

So the actual problem is not in the signed assembly anymore, but in the "internals-visible-to" reference.

e.g. for EntityFramework.Core

```C#
[assembly: InternalsVisibleTo("EntityFramework.SqlServer.Tests")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("EntityFramework.Core.Tests")]
```

**Comment by divega** [comment]
Moving to rc1 which I believe is the right milestone for it. We can probably close it soon.

cc @rowanmiller @bricelam

**Comment by bricelam** [comment]
Our assemblies in the nightly feed are now signed.

**Comment by rowanmiller** [comment]
Closing as everything should be strong named in RC1 (and future releases) now
